### PR TITLE
[radio] clarify `mTimestamp` meaning in comments

### LINKED ISSUE #8888: Clarify requirement for "SFD timestamp" in radio.h
**Describe the bug** 
There is code in `radio.h` 

```
             /**
             * The timestamp when the frame was received in microseconds.
             *
             * The value SHALL be the time when the SFD was received when TIME_SYNC or CSL is enabled.
             * Otherwise, the time when the MAC frame was fully received is also acceptable.
             *
             */
            uint64_t mTimestamp;

```

It's not clear if mTimestamp shall be start of first symbol of SFD, or end of last symbol of SFD (i.e. after it has been received). Platforms could use different interpretations which leads to a 32 us time difference in CSL timing between platforms, potentially.

**To Reproduce** 

Latest commit.

**Expected behavior**
Comment should indicate for `mTimestamp` if the time is 
1. the start of the first symbol of SFD, or
2. the end of the last symbol of SFD
3. time exactly in between first and last symbol (Maybe :) )

### PR DESCRIPTION
**Pull request by EskoDijk**
close #8888

### CODE REVIEW

File: include/openthread/platform/radio.h [hunk 1]
```diff
@@ -334,7 +334,8 @@ typedef struct otRadioFrame
             /**
              * The timestamp when the frame was received in microseconds.
              *
-             * The value SHALL be the time when the SFD was received when TIME_SYNC or CSL is enabled.
+             * The value SHALL be the time when the SFD was fully received when TIME_SYNC or CSL is enabled.
+             * (That is, the time that marks the end of reception of the last symbol of the SFD.)
              * Otherwise, the time when the MAC frame was fully received is also acceptable.
```
Comment (abtink) [inline include/openthread/platform/radio.h:339]: Since we have a change to platform header, we need to increment the `OPENTHREAD_API_VERSION` in `intsnace.h`.

GH action "API Version" checks this -> https://github.com/openthread/openthread/actions/runs/4492127980/jobs/7901580504?pr=8894

**Review by abtink — APPROVED** [review]
LGTM. Thanks @EskoDijk . 👍 
One suggestion below.

Also for commit/PR title, we can consider "[radio] clarify `mTimestamp` meaning in comment" ?

File: src/core/mac/mac_frame.hpp [hunk 2]
```diff
@@ -1206,6 +1206,8 @@ class RxFrame : public Frame
 
     /**
      * This method returns the timestamp when the frame was received.
+     * If CSL or TIME_SYNC is enabled, the timestamp marks the frame detection time: the end of the last symbol of SFD.
+     * If CSL and TIME_SYNC are both not enabled, it may also mark the end of the last symbol of the frame.
```
Comment (Vyrastas) [inline src/core/mac/mac_frame.hpp:1210]: If neither CSL nor TIME_SYNC are enabled,

File: include/openthread/platform/radio.h (hunk 1 above)
Comment (EskoDijk) [reply include/openthread/platform/radio.h:339]: Done; this sounds like one of the SW developer bedtime stories "... and then the automated tests became so complex that even changing a comment line would fail the tests ... "  ;-)

File: src/core/mac/mac_frame.hpp (hunk 2 above)
Comment (EskoDijk) [reply src/core/mac/mac_frame.hpp]: Updated now; I had a few instances were an editor corrected away my use of "neither ... nor" so I tried to explicitly avoid it here ;-)

**Review by Vyrastas — APPROVED** [review]

File: src/core/mac/mac_frame.hpp (hunk 2 above)
Comment (Vyrastas) [reply src/core/mac/mac_frame.hpp]: Thanks, now that I think of it, I suppose we could also say

"If CSL and TIME_SYNC are both disabled"

Neither/nor just came to mind first

File: src/core/mac/mac_frame.hpp [hunk 3]
```diff
@@ -1206,6 +1206,8 @@ class RxFrame : public Frame
 
     /**
      * This method returns the timestamp when the frame was received.
+     * If CSL or TIME_SYNC is enabled, the timestamp marks the frame detection time: the end of the last symbol of SFD.
+     * If neither CSL nor TIME_SYNC are enabled, it may also mark the end of the last symbol of the frame.
```
Comment (jwhui) [inline src/core/mac/mac_frame.hpp:1210]: Do we actually use a timestamp that marks the end of the frame? Why not always mark end of SFD?

Comment (jwhui) [reply src/core/mac/mac_frame.hpp:1210]: Given the timestamp of the end of frame, it should be possible to compute the timestamp of the SFD as well, right?

Comment (EskoDijk) [reply src/core/mac/mac_frame.hpp:1210]: Yes, certainly. Though for a simple platform not supporting CSL this would not be needed; it then adds extra code which would have no perceivable effect . But to avoid confusion it's also fine to be clear that timestamp is SFD time. E.g. like 

```
* The timestamp marks the frame detection time: the end of the last symbol of SFD.
* The accuracy of the timestamp is platform-dependent.
```

Maybe go for that?

Comment (jwhui) [reply src/core/mac/mac_frame.hpp:1210]: Yes, I think it is simpler if this timestamp always has the same meaning, regardless of platform capabiltiies.

I think we can simplify to just the first line:
```
* The timestamp marks the frame detection time: the end of the last symbol of SFD.
```

File: include/openthread/platform/radio.h (hunk 1 above)
Comment (jwhui) [inline include/openthread/platform/radio.h:339]: I think we can simplify this to:
```
* The value SHALL be the time when the SFD was received.
```

File: src/core/mac/mac_frame.hpp (hunk 3 above)
Comment (EskoDijk) [reply src/core/mac/mac_frame.hpp]: Ok, updated now!

File: include/openthread/platform/radio.h (hunk 1 above)
Comment (EskoDijk) [reply include/openthread/platform/radio.h]: Ok, updated now!

**Review by Vyrastas — APPROVED** [review]

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼
