### PR TITLE
[nrf52840] Fix HF clock stop procedure in radio driver

### LINKED ISSUE #2380: [nrf52480] Calling nrf_drv_radio802154_fsm_sleep() breaks usb-cdc-uart transmit
I am currently working on bringing up a nRF52480-based NCP that uses its native USB capabilities to communicate with the application/host processor, using [USB-CDC-ACM UART implementation](https://github.com/openthread/openthread/blob/master/examples/platforms/nrf52840/usb-cdc-uart.c) (Added in #2215, documented [here](https://github.com/openthread/openthread/tree/master/examples/platforms/nrf52840#native-usb-support)).

At first it seemed like it was working fairly well, but then I noticed that the NCP would become unresponsive after receiving certain commands. Depending on the command there were a few different reasons for this, but this bug is about the freeze that would happen after doing something like setting `PROP_NET_STACK_UP` to false.

When I would set `PROP_NET_STACK_UP` to false, I would no longer receive any output on the USB-CDC-ACM port. However, I know that the commands I was sending it were being received and processed.

Looking into the issue further made me realize that `ncp_uart.cpp` had called `otPlatUartSend()` to send the host the next frame, but `otPlatUartSendDone()` was not being called. Digging into this further, I determined that one of the results of setting `PROP_NET_STACK_UP` to false is a call to `otPlatRadioSleep()`. When I modified this function to return without doing anything, setting `PROP_NET_STACK_UP` to false would succeed.

Digging even further, I narrowed down the problem to the call to `nrf_drv_radio802154_fsm_sleep()` (Called from `nrf_drv_radio802154_request_sleep()`, which is called from `nrf_drv_radio802154_sleep()`, which is called from `otPlatRadioSleep()`). Calling `nrf_drv_radio802154_fsm_sleep()` somehow seems to quite reliably prevent future calls to `app_usbd_cdc_acm_write()` from triggering `APP_USBD_CDC_ACM_USER_EVT_TX_DONE`. It does not, however, prevent `APP_USBD_CDC_ACM_USER_EVT_RX_DONE` from being triggered, as even in this state the NCP continues to process inbound frames.

### PR DESCRIPTION
**Pull request by hubertmis**
Should fix #2380 . I don't have NCP USB setup to test it, but I've verified that now radio driver uses clock driver to enable and disable HF clock.

### CODE REVIEW

**Comment by darconeous** [comment]
Will test.

File: third_party/NordicSemiconductor/hal/nrf_egu.h [hunk 1]
```diff
@@ -45,8 +45,6 @@
 #include "nrf.h"
 #include "nrf_peripherals.h"
 
-#define ASSERT assert
```
Comment (darconeous) [inline third_party/NordicSemiconductor/hal/nrf_egu.h]: The removal of this line gives me a compiler error:

```
In file included from /usr/local/google/home/rquattle/Projects/openthread/examples/../examples/platforms/nrf52840/../../../third_party/NordicSemiconductor/drivers/radio/nrf_drv_radio802154_swi.c:48:0:
/usr/local/google/home/rquattle/Projects/openthread/examples/../third_party/NordicSemiconductor/hal/nrf_egu.h: In function 'nrf_egu_task_trigger_address_get':
/usr/local/google/home/rquattle/Projects/openthread/examples/../third_party/NordicSemiconductor/hal/nrf_egu.h:194:5: error: implicit declaration of function 'ASSERT' [-Wimplicit-function-declaration]
     ASSERT(channel < nrf_egu_channel_count(NRF_EGUx));
     ^
make[5]: *** [../../../third_party/NordicSemiconductor/drivers/radio/libopenthread_nrf52840_softdevice_sdk_a-nrf_drv_radio802154_swi.o] Error 1
```

File: examples/platforms/nrf52840/platform-config.h [hunk 2]
```diff
@@ -334,4 +336,56 @@
...
+#define NRF_DRV_RADIO802154_PENDING_EXTENDED_ADDRESSES  OPENTHREAD_CONFIG_MAX_CHILDREN
+#endif
+
+/**
+ * @def NRF_RAAL_HFCLK_START
+ *
+ * Macro to request High Frequency Clock start. It may use external driver or OS function.
+ *
+ */
+#ifndef NRF_RAAL_HFCLK_START
```
Comment (darconeous) [inline examples/platforms/nrf52840/platform-config.h]: Wouldn't we want to fail hard here (or at least emit a warning) if this was already defined?

File: third_party/NordicSemiconductor/hal/nrf_egu.h (hunk 1 above)
Comment (darconeous) [reply third_party/NordicSemiconductor/hal/nrf_egu.h]: Nevermind. I forgot to run `bootstrap`.
