### PR TITLE
[dnssd] echo all questions in the response on `NameError`

### LINKED ISSUE #11505: DNS answer question count not set in case of NXDOMAIN response
**Describe the bug** A clear and concise description of what the bug is.

See below code - in tests and simulation I've seen that the DNS answer QCOUNT is not set to 1, incase the RCode is set to NXDOMAIN. However the data for the question section is appended.  

It seems the `VerifyOrExit()` prevents the `SetQuestionCount` to execute.

```
Server::ResponseCode Server::Response::AddQuestionsFrom(const Request &aRequest)
{
    ResponseCode rcode = Header::kResponseServerFailure;
    uint16_t     offset;

    mQuestions = aRequest.mQuestions;

    // Read the name from `aRequest.mMessage` and append it as is to
    // the response message. This ensures all name formats, including
    // service instance names with dot characters in the instance
    // label, are appended correctly.

    SuccessOrExit(Name(*aRequest.mMessage, kQueryNameOffset).AppendTo(*mMessage));

    // Check the name to include the correct domain name and determine
    // the domain name offset (for DNS name compression).

    VerifyOrExit(ParseQueryName() == kErrorNone, rcode = Header::kResponseNameError);

    mHeader.SetQuestionCount(aRequest.mHeader.GetQuestionCount());
```

**To Reproduce** Information to reproduce the behavior, including:

Latest OT; one BR and one client; client sends
`ot dns resolve ipv4only.arpa`  or
`ot dns resolve4 ipv4only.arpa`  

**Expected behavior** A clear and concise description of what you expected to happen.

QCOUNT should be set to '1' also if NXDOMAIN (`kResponseNameError`) is already set in the answer.
Any type of error should still echo the question back.

In general, it may be possible to add a QCOUNT=1 validation to all DNS answers, as a default, if there is some default DNS answer validation routine.  (Obviously not when 2-question queries are being tested.)

**Console/log output** If applicable, add console/log output to help explain your problem.

**Additional context** Add any other context about the problem here.

### PR DESCRIPTION
**Pull request by abtink**
This commit updates the DNSSD server/resolver to ensure it includes the questions in the response message when the returned RCODE is `NameError` (NXDOMAIN). It also clears the question count and any partially appended content if there is a failure to append all questions (when `kResponseServerFailure` (SERVFAIL) is returned).

It also adds a test case in `test_dns_client` to resolve a non-existent name and validate the included questions.

---

- Resolves #11505

### CODE REVIEW

File: tests/unit/test_dns_client.cpp [hunk 1]
```diff
@@ -804,6 +805,16 @@ void TestDnsClient(void)
...
 
+    //- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
+    // Validate DNS Client `ResolveAddress()` for an invalid (non-existing) name
+
+    sAddressInfo.Reset();
+    Log("ResolveAddress(%s)", kNonExistingName);
+    SuccessOrQuit(dnsClient->ResolveAddress(kNonExistingName, AddressCallback, sInstance));
+    AdvanceTime(100);
+    VerifyOrQuit(sAddressInfo.mCallbackCount == 1);
+    VerifyOrQuit(sAddressInfo.mError == kErrorNotFound);
```
Comment (EskoDijk) [inline tests/unit/test_dns_client.cpp:816]: Is there a way to check here that the question-count in the answer is 1 ? This could be done for the valid name query and the invalid name query.

Comment (abtink) [reply tests/unit/test_dns_client.cpp:816]: No, I don't think there's an easy way to validate this in the unit test, as the parsed error code and/or the parsed result (e.g., IPv6 addresses) are provided in the callback. It's not worth adding new code and machinery just to test this.

Comment (EskoDijk) [reply tests/unit/test_dns_client.cpp:816]: Right, agree that no code needs to be added only for that!

**Review by EskoDijk — APPROVED** [review]
@abtink Thanks, this solves the issue!

**Review by jwhui — APPROVED** [review]
