### PR TITLE
[mac] process security for neighbors on FFD Children

### LINKED ISSUE #2364: REED and FED receiving of multicasts from neighboring routers
According to section 4.7.7.4 of thread spec 1.1.1 REEDs and FEDs must maintain one-way links with neighboring routers so that the REED/FED can receive MAC-secured multicasts from them. Currently in openthread FEDs/REEDs use link requests & accepts as required, but drop incoming MAC-secured transmissions that are not from their parents.

This is because the method of validating a MAC source address uses GetNeighbor(), which switches on the current role:
https://github.com/openthread/openthread/blob/1f6528e6c9a600b7f04128ed8f22e841107361f6/src/core/mac/mac.cpp#L1572-L1576
Of course, this behaviour of GetNeighbor is usually needed, so perhaps a special case in Mac.cpp to check the router table too, in the case of an FFD child receiving a broadcast frame?

Example Logs (I used an address query from a non-parent router to generate):
Child establishing one way link:
```
[6] [INFO]-MLE-----: Receive Advertisement (fe80:0:0:0:2c18:59bb:9377:9a0f,0x8000)
[6] [INFO]-MLE-----: Send Link Request (fe80:0:0:0:2c18:59bb:9377:9a0f)
[6] [INFO]-MAC-----: Sent IPv6 UDP msg, len:92, chksum:1cb5, to:2e1859bb93779a0f, sec:no, prio:high
[6] [INFO]-MAC-----: src: fe80:0:0:0:1432:68b9:eb2d:53b7
[6] [INFO]-MAC-----: dst: fe80:0:0:0:2c18:59bb:9377:9a0f
[6] [INFO]-MAC-----: Received IPv6 UDP msg, len:97, chksum:8e81, from:2e1859bb93779a0f, sec:no, prio:low, rss:-20.0
[6] [INFO]-MAC-----: src: fe80:0:0:0:2c18:59bb:9377:9a0f
[6] [INFO]-MAC-----: dst: fe80:0:0:0:1432:68b9:eb2d:53b7
[6] [INFO]-MLE-----: Receive Link Accept (fe80:0:0:0:2c18:59bb:9377:9a0f,0x8000)
```

Router table of child:
```
router table[6] [INFO]---------: execute command: router table

| ID | RLOC16 | Next Hop | Path Cost | LQ In | LQ Out | Age | Extended MAC     |
+----+--------+----------+-----------+-------+--------+-----+------------------+
| 29 | 0x7400 |       29 |         1 |     0 |      0 |  41 | 0000000000000000 |
| 32 | 0x8000 |        0 |         0 |     3 |      3 |   4 | 2e1859bb93779a0f |

Done
```

And the filtering upon receiving of a multicast:
```
[6] [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:65, seqnum:195, type:Data, src:0x8000, dst:0xffff, sec:yes, ackreq:no
[6] [INFO]-MAC-----: Frame rx failed, error:UnknownNeighbor, len:65, seqnum:196, type:Data, src:0x8000, dst:0xffff, sec:yes, ackreq:no
```

### PR DESCRIPTION
**Pull request by CiaranWoodward**
Fixes #2364 

Also simplified the existing MleRouter::GetNeighbor() slightly

### CODE REVIEW

File: src/core/mac/mac.cpp [hunk 1]
```diff
@@ -1571,8 +1571,53 @@ void Mac::ReceiveDoneTask(Frame *aFrame, otError aError)
...
+        aFrame->GetDstPanId(panid);
+        VerifyOrExit((panid == kShortAddrBroadcast || panid == mPanId) &&
+                     ((mRxOnWhenIdle && dstaddr.mShortAddress == kShortAddrBroadcast) ||
+                      dstaddr.mShortAddress == mShortAddress), error = OT_ERROR_DESTINATION_ADDRESS_FILTERED);
+
+#if OPENTHREAD_FTD
+
+        // Allow non link-local multicasts from neighbor routers if FFD
+        if (neighbor == NULL && dstaddr.mShortAddress == kShortAddrBroadcast &&
+            srcaddr.mLength == sizeof(ShortAddress) &&
```
Comment (jwhui) [inline src/core/mac/mac.cpp]: I understand this predicate is meant to only accept non-link-local multicasts.  Strictly speaking, however, I don't think the Thread spec prohibits the use of short MAC source address with link-local multicast messages.  In any case, is this check really necessary to include?

File: src/core/mac/mac.cpp [hunk 2]
```diff
@@ -1571,8 +1571,53 @@ void Mac::ReceiveDoneTask(Frame *aFrame, otError aError)
...
+            GetNetif().GetMle().IsActiveRouter(srcaddr.mShortAddress) &&
```
Comment (jwhui) [inline src/core/mac/mac.cpp]: Is this check necessary?  I believe all neighbors in the valid state should be active routers.

Comment (CiaranWoodward) [reply src/core/mac/mac.cpp]: The IsActiveRouter function just checks the RLOC16 has a Child ID of 0, and is related to how I obtain the router object below (Otherwise a child RLOC would be accepted but the ```neighbor``` pointer would refer to the parent). I think I'm going to abstract this away, because it did make for an ugly bloated if condition, and I can also remove the preprocessor conditionals.

File: src/core/mac/mac.cpp (hunk 1 above)
Comment (CiaranWoodward) [reply src/core/mac/mac.cpp]: That was intended to be a confirmation that the below ```IsActiveRouter``` and ```GetRouterId``` functions would work, so it was more important that it didn't falsely filter out frames that should be received. I do agree that it perhaps over constrains this part, as the only frames that MUST be discarded are multicasts, so I'll tidy up
