### PR TITLE
[auto-start] remove auto-start feature

### LINKED ISSUE #3685: [posix-app] auto start support with platform netif enabled
Auto start is now implemented in ot instance init. Giving no chance init other components including platform netif. We should change the design, possibly trigger auto start in a tasklet.

### LINKED ISSUE #3755: nrf52840-dongle's  ot-ncp fails with uninitialized:fault
Hi folks, I know that a related issue was closed a few months ago (https://github.com/openthread/openthread/issues/3087) but I have the same problem here. Since it ended up straying a bit from the original problem and issuer did not follow up on the resolution, I'm asking again.

> * Commit ID for NCP firmware.
> * Commit ID for wpantund.
> * Build command/configuration you used for NCP firmware.

```
menezes@prime:~/wpantund$ git show
commit 42f9b6e553ebb0ed652ea8212b53c652865da19a (HEAD -> master, origin/master, origin/HEAD)
Author: Yakun Xu <xyk@google.com>
Date:   Sat Mar 30 02:08:09 2019 +0800

menezes@prime:~/openthread$ git show
commit 19544490e37a88642f5e016388038a9ac9def174 (HEAD -> master, origin/master, origin/HEAD)
Author: Jonathan Hui <jonhui@google.com>
Date:   Thu Mar 28 22:29:58 2019 -0700

menezes@prime:~/openthread$ make -f examples/Makefile-nrf52840 COMMISSIONER=1 JOINER=1 COAP=1 DNS_CLIENT=1 MTD_NETDIAG=1 BORDER_ROUTER=1 MAC_FILTER=1 UDP_PROXY=1 BORDER_AGENT=1 LINK_RAW=1 SERVICE=1 USB=1 BOOTLOADER=1
menezes@prime:~/openthread$ arm-none-eabi-objcopy output/nrf52840/bin/ot-ncp-ftd -O ihex output/nrf52840/bin/ot-ncp-ftd.hex
```

I flashed the hex file using nrfconnect. 

The really funny thing is that I can connect to the NCP using pyspinel and the command _state_ returns _leader_ as it should. I also got working the NCP using the posix socket (ot-cli OR wpantund + ot-ncp) with the ot-ncp-radio firmware flashed in the dongle.

dmesg also seems right when I remove and insert back the dongle:

```
[mar29 19:37] usb 3-3: USB disconnect, device number 19
[  +7,976417] usb 3-3: new full-speed USB device number 20 using xhci_hcd
[  +0,150903] usb 3-3: New USB device found, idVendor=1915, idProduct=cafe
[  +0,000008] usb 3-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  +0,000004] usb 3-3: Product: nRF52840 OpenThread Device
[  +0,000005] usb 3-3: Manufacturer: Nordic Semiconductor
[  +0,000004] usb 3-3: SerialNumber: E20EFXXXXXXX
[  +0,002014] cdc_acm 3-3:1.1: ttyACM0: USB ACM device
```

My wpantund.conf:

```
Config:NCP:SocketPath "/dev/ttyACM0"
Config:NCP:DriverName spinel
Daemon:SyslogMask "all"
```

Output from wpantund after reseting the NCP using wpanctl:

```
menezes@prime:~/wpantund$ sudo wpantund
wpantund[28434]: Starting wpantund 0.08.00d (Mar 29 2019 15:25:58) . . .
wpantund[28434]:     SOURCE_VERSION = 0.07.01-286-g42f9b6e
wpantund[28434]:     BUILD_VERSION = 0.07.01-286-g42f9b6e
wpantund[28434]: Configuration file "/etc/wpantund.conf" read.
wpantund[28434]: set-config-param: "Daemon:SyslogMask" set succeded
wpantund[28434]: Stat (autolog): Tx: 0 packets (0 udp, 0 tcp, 0 icmp6) -- 0 bytes
wpantund[28434]: Stat (autolog): Tx history is empty
wpantund[28434]: Stat (autolog):
wpantund[28434]: Stat (autolog): Rx: 0 packets (0 udp, 0 tcp, 0 icmp6) -- 0 bytes
wpantund[28434]: Stat (autolog): Rx history is empty
wpantund[28434]: Stat (autolog):
wpantund[28434]: Stat (autolog): NCP state history is empty.
wpantund[28434]: Stat (autolog):
wpantund[28434]: Stat (autolog):
wpantund[28434]: Opening tun interface socket with name "wpan0"
wpantund[28434]: Getting DBus connection
wpantund[28434]: Registering DBus connection
wpantund[28434]: Requesting DBus connection name com.nestlabs.WPANTunnelDriver
wpantund[28434]: Ready. Using DBUS bus ":1.183"
wpantund[28434]: Running as root without dropping privileges!
wpantund[28434]: Initializing NCP
wpantund[28434]: Removing all NCP originated addresses
wpantund[28434]: NCP is now BUSY.
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(LAST_STATUS) [70]
wpantund[28434]: [-NCP-]: Last status (RESET_POWER_ON, 112)
wpantund[28434]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(IPV6_ADDRESS_TABLE) [1900FDDEAD00BEEF...]
wpantund[28434]: [-NCP-]: IPv6 address [0] "fdde:ad00:beef::ff:fe00:fc00"
wpantund[28434]: [-NCP-]: IPv6 address [1] "fdde:ad00:beef::ff:fe00:a800"
wpantund[28434]: UnicastAddresses: Adding "fdde:ad00:beef::ff:fe00:a800/64", origin:ncp, valid:forever, preferred:forever
wpantund[28434]: [-NCP-]: IPv6 address [2] "fdde:ad00:beef:0:5172:1430:edec:9cb6"
wpantund[28434]: UnicastAddresses: Adding "fdde:ad00:beef:0:5172:1430:edec:9cb6/64", origin:ncp, valid:forever, preferred:forever
wpantund[28434]: [-NCP-]: IPv6 address [3] "fe80::149b:7b0f:1c33:cba"
wpantund[28434]: UnicastAddresses: Adding "fe80::149b:7b0f:1c33:cba/64", origin:ncp, valid:forever, preferred:forever
wpantund[28434]: [-NCP-]: IPv6 address: Total 4 addresses
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(NET_ROLE) [03]
wpantund[28434]: [-NCP-]: Net Role "NET_ROLE_LEADER" (3)
wpantund[28434]: Node type change: "unknown" -> "leader"
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(NET_PARTITION_ID) [43908652]
wpantund[28434]: [-NCP-] Partition id: 1384550467 (0x52869043)
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_LEADER_NETWORK_DATA) [08040B025769]
wpantund[28434]: [-NCP-] Leader network data: [08040B025769]
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_ON_MESH_NETS) []
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_OFF_MESH_ROUTES) []
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(IPV6_MULTICAST_ADDRESS_TABLE) [1000FF330040FDDE...]
wpantund[28434]: [-NCP-]: Multicast IPv6 address [0] "ff33:40:fdde:ad00:beef::1"
wpantund[28434]: MulticastAddresses: Adding "ff33:40:fdde:ad00:beef::1", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [1] "ff32:40:fdde:ad00:beef::1"
wpantund[28434]: MulticastAddresses: Adding "ff32:40:fdde:ad00:beef::1", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [2] "ff02::2"
wpantund[28434]: MulticastAddresses: Adding "ff02::2", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [3] "ff03::2"
wpantund[28434]: MulticastAddresses: Adding "ff03::2", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [4] "ff02::1"
wpantund[28434]: MulticastAddresses: Adding "ff02::1", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [5] "ff03::1"
wpantund[28434]: MulticastAddresses: Adding "ff03::1", origin:ncp
wpantund[28434]: [-NCP-]: Multicast IPv6 address [6] "ff03::fc"
wpantund[28434]: MulticastAddresses: Adding "ff03::fc", origin:ncp
wpantund[28434]: [->NCP] (1) PROP_VALUE_GET(PROTOCOL_VERSION)
wpantund[28434]: [NCP->] (1) PROP_VALUE_IS(PROTOCOL_VERSION) [0403]
wpantund[28434]: [->NCP] (2) PROP_VALUE_GET(NET_STACK_UP)
wpantund[28434]: [NCP->] (2) PROP_VALUE_IS(NET_STACK_UP) [01]
wpantund[28434]: [-NCP-]: Stack is up

wpantund[28434]: State change: "uninitialized" -> "associating"
wpantund[28434]: SpinelNCPInstance-Protothreads.cpp:430: Requirement Failed (!ncp_state_is_joining(get_ncp_state()))

wpantund[28434]: Resetting and trying again... (retry 1)
wpantund[28434]: State change: "associating" -> "uninitialized"
wpantund[28434]: [->NCP] (3) RESET
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(LAST_STATUS) [70]
wpantund[28434]: [-NCP-]: Last status (RESET_POWER_ON, 112)
wpantund[28434]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
wpantund[28434]: [->NCP] (4) PROP_VALUE_GET(PROTOCOL_VERSION)
wpantund[28434]: [NCP->] (4) PROP_VALUE_IS(PROTOCOL_VERSION) [0403]
wpantund[28434]: [->NCP] (5) PROP_VALUE_GET(NET_STACK_UP)
wpantund[28434]: [NCP->] (5) PROP_VALUE_IS(NET_STACK_UP) [01]
wpantund[28434]: [-NCP-]: Stack is up

wpantund[28434]: State change: "uninitialized" -> "associating"
wpantund[28434]: SpinelNCPInstance-Protothreads.cpp:430: Requirement Failed (!ncp_state_is_joining(get_ncp_state()))

wpantund[28434]: Resetting and trying again... (retry 2)
wpantund[28434]: State change: "associating" -> "uninitialized"
wpantund[28434]: SuperSocket::reset()
wpantund[28434]: SpinelNCPInstance-Protothreads.cpp:400: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(IPV6_ADDRESS_TABLE) [1900FDDEAD00BEEF...]
wpantund[28434]: [-NCP-]: IPv6 address [0] "fdde:ad00:beef::ff:fe00:fc00"
wpantund[28434]: [-NCP-]: IPv6 address [1] "fdde:ad00:beef::ff:fe00:a800"
wpantund[28434]: [-NCP-]: IPv6 address [2] "fdde:ad00:beef:0:5172:1430:edec:9cb6"
wpantund[28434]: [-NCP-]: IPv6 address [3] "fe80::149b:7b0f:1c33:cba"
wpantund[28434]: [-NCP-]: IPv6 address: Total 4 addresses
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(NET_ROLE) [03]
wpantund[28434]: [-NCP-]: Net Role "NET_ROLE_LEADER" (3)
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(NET_PARTITION_ID) [F5428453]
wpantund[28434]: [-NCP-] Partition id: 1401176821 (0x538442f5)
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_LEADER_NETWORK_DATA) [08040B0229E8]
wpantund[28434]: [-NCP-] Leader network data: [08040B0229E8]
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_ON_MESH_NETS) []
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(THREAD_OFF_MESH_ROUTES) []
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(IPV6_MULTICAST_ADDRESS_TABLE) [1000FF330040FDDE...]
wpantund[28434]: [-NCP-]: Multicast IPv6 address [0] "ff33:40:fdde:ad00:beef::1"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [1] "ff32:40:fdde:ad00:beef::1"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [2] "ff02::2"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [3] "ff03::2"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [4] "ff02::1"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [5] "ff03::1"
wpantund[28434]: [-NCP-]: Multicast IPv6 address [6] "ff03::fc"

wpantund[28434]: Resetting and trying again... (retry 3)
wpantund[28434]: [->NCP] (6) RESET
wpantund[28434]: [NCP->] (0) PROP_VALUE_IS(LAST_STATUS) [70]
wpantund[28434]: [-NCP-]: Last status (RESET_POWER_ON, 112)
wpantund[28434]: [-NCP-]: NCP was reset (RESET_POWER_ON, 112)
wpantund[28434]: [->NCP] (7) PROP_VALUE_GET(PROTOCOL_VERSION)
wpantund[28434]: [NCP->] (7) PROP_VALUE_IS(PROTOCOL_VERSION) [0403]
wpantund[28434]: [->NCP] (8) PROP_VALUE_GET(NET_STACK_UP)
wpantund[28434]: [NCP->] (8) PROP_VALUE_IS(NET_STACK_UP) [01]
wpantund[28434]: [-NCP-]: Stack is up

wpantund[28434]: State change: "uninitialized" -> "associating"
wpantund[28434]: SpinelNCPInstance-Protothreads.cpp:430: Requirement Failed (!ncp_state_is_joining(get_ncp_state()))
wpantund[28434]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
wpantund[28434]: State change: "associating" -> "uninitialized:fault"
wpantund[28434]: DBus Sending Interface Added Signal for wpan0
^C
```

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #3685.
Resolves #3755.

### CODE REVIEW

File: src/core/openthread-core-config-check.h [hunk 1]
```diff
@@ -54,7 +54,11 @@
 #endif
 
 #ifdef OPENTHREAD_CONFIG_MAX_SERVER_ALOCS
-#error "OPENTHREAD_CONFIG_MAX_SERVER_ALOCS was replaced by OPENTHREAD_CONFIG_MAX_SERVICE_ALOCS"
+#error "OPENTHREAD_CONFIG_MAX_SERVER_ALOCS was replaced by OPENTHREAD_CONFIG_MAX_SERVICE_ALOCS."
+#endif
+
+#ifdef OPENTHREAD_CONFIG_ENABLE_AUTO_START_SUPPORT
+#error "OPENTHREAD_CONFIG_ENABLE_AUTO_START_SUPPORT was removed."
```
Comment (abtink) [inline src/core/openthread-core-config-check.h]: 👍
