### PR TITLE
[mle] fix bug in leader active/pending dataset synchronization

### LINKED ISSUE #5020: [MeshCoP] Flood of MGMT_ACTIVE_SET.req from peer devices to leader
**Describe the bug** A clear and concise description of what the bug is.

A leader will reject MGMT_ACTIVE_SET.req from peer devices if it crashes during the handling of a prior request. Peer devices don't know how to handle rejection, and will initiate new transactions forever.

The additional MeshCoP traffic impacts the application layer's performance.

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id 
    d281be6aefe518f501719b39007fda8905c03eb6
2. IEEE 802.15.4 hardware platform 
    nrf52840 development kits with ot-cli-ftd images built from this repository
3. Build steps
     ```
    make -f examples/Makefile-nrf52840 USB=1 DEBUG=1 FULL_LOGS=1 LINK_RAW=1 COMMISSIONER=1 JOINER=1 BORDER_ROUTER=1 BORDER_AGENT=1
    ```
4. Network topology 
    Single leader, single peer (router)

It's hard to restart at exactly the right time. [This branch](https://github.com/MatthewPennock/openthread/tree/meshcop_mgmt_active_set_flood) helps reproductions with a `prime` command which makes devices restart while handling MGMT_ACTIVE_SET.req commands.

1. Form a network with two devices:
    To leader:
    ```
    dataset init new
    dataset channel 25
    dataset masterkey 00112233445566778899aabbccddeeff
    dataset commit active
    ifconfig up
    thread start
    ```
    To peer:
    ```
    dataset masterkey 00112233445566778899aabbccddeeff
    dataset active commit
    ifconfig up
    thread start
    ```
2. Inspect datasets (optional, useful to compare against after a reset)
    To leader:
    ````
    > state
    leader
    Done
    > dataset active
    Active Timestamp: 1
    Channel: 25
    Channel Mask: 07fff800
    Ext PAN ID: 742c6bb30e104f47
    Mesh Local Prefix: fde7:613b:9f35:f257/64
    Master Key: 00112233445566778899aabbccddeeff
    Network Name: OpenThread-9cca
    PAN ID: 0x9cca
    PSKc: 64605993860134ac689f783ab7be7c09
    Security Policy: 0, onrcb
    Done
    ````
    To peer:
    ````
    > state
    router
    Done
    > dataset active
    Active Timestamp: 1
    Channel: 25
    Channel Mask: 07fff800
    Ext PAN ID: 742c6bb30e104f47
    Mesh Local Prefix: fde7:613b:9f35:f257/64
    Master Key: 00112233445566778899aabbccddeeff
    Network Name: OpenThread-9cca
    PAN ID: 0x9cca
    PSKc: 64605993860134ac689f783ab7be7c09
    Security Policy: 0, onrcb
    Done
    ````
3. Roll back leader's timestamp:
    To leader:
    ```
    dataset activetimestamp 0
    prime
    dataset commit active
    ```
4. Have the leader rejoin the network:
    To leader:
    ```
    ifconfig up
    thread start
    ```
Step #3 forces all devices to send the leader a MGMT_ACTIVE_SET.req. The leader will restart while handling the first, but after committing the peer's more recent dataset (I believe). The `StateTlv::kAccept` response is lost in a queue, so our peers are unaware their petition succeeded.

New MGMT_ACTIVE_SET requests will be generated endlessly.

**Expected behavior** A clear and concise description of what you expected to happen.

A leader could encourage peers to seek out new data sets by increment the MLE data version (as suggested by Jonathan Hui). However, my ultra naive implementation has only made the problem worse! 

**Console/log output** If applicable, add console/log output to help explain your problem.

1. Leader's SEGGER RTT log output: 
[leader_rtt.log](https://github.com/openthread/openthread/files/4697976/leader_rtt.log)

2. Peer's SEGGER RTT log output: 
[router_rtt.log](https://github.com/openthread/openthread/files/4697977/router_rtt.log)

3. Wireshark capture: 
[flood.zip](https://github.com/openthread/openthread/files/4697982/flood.zip)
    Link Key: 00112233445566778899aabbccddeeff

**Additional context** Add any other context about the problem here.

The RTT logs in this instance show a more complete picture as the leader becomes trapped in a rapid-fire conversation with itself. I hope to follow up very shortly with a reproduction using a previous commit to master (before new MeshCoP transactions were only initiated after CoAP's complete 93 second timeout) and without my increment of data version.

Thank you,
Matt

### PR DESCRIPTION
**Pull request by jwhui**
The leader is the authoritative source when propagating active/pending
operational datasets. When the leader reboots, it is possible for the
leader to become out-of-sync. In particular, after the leader resets,
it restores its network data and active/pending operational datasets
using MLE Data Request/Response to retrieve them from a neighboring
device. If the neighboring device has an older active/pending
operational dataset, the leader will retrieve the older datasets and
never attempt to propagate the newer datasets that it may have stored
locally.

This commit makes the following changes:

- The leader does not accept any changes to the active/pending
  operational datasets.

- After retrieving the latest network data from a neighboring device
  (as part of resynchronizing after reset), the leader will increment
  the full and stable network data versions to ensure that the leader
  propagates the latest active/pending operational datasets.

Resolves #5020.

### CODE REVIEW

File: src/core/thread/mle.cpp [hunk 1]
```diff
@@ -3032,6 +3032,9 @@ otError Mle::HandleLeaderData(const Message &aMessage, const Ip6::MessageInfo &a
         // if received timestamp does not match the local value and message does not contain the dataset,
         // send MLE Data Request
         if ((timestamp == NULL || timestamp->Compare(activeTimestamp) != 0) &&
+#if OPENTHREAD_FTD
```
Comment (wgtdkp) [inline src/core/thread/mle.cpp:3035]: nit: this seems not readable. How about defining `IsLeader` like below:
```C++
#if OPENTHREAD_FTD
    ...
#else
    bool IsLeader() const { return false; }
#endif 
```

I think the compiler can optimize out `IsLeader` when `OPENTHREAD_FTD` is not defined, so the code side should not affected.

**Comment by MatthewPennock** [comment]
I wholeheartedly approve of 644acab96e090dcbc0fb38261ffd06847694ad22! 

Bench testing results:

Leader RTT: [leader_rtt.log](https://github.com/openthread/openthread/files/4702228/leader_rtt.log)
Router RTT: [router_rtt.log](https://github.com/openthread/openthread/files/4702232/router_rtt.log)
Wireshark: [openthread_5020.zip](https://github.com/openthread/openthread/files/4702234/openthread_5020.zip)
Master Key: 00112233445566778899aabbccddeeff

Thank you @jwhui for taking on the fix!

**Comment by jwhui** [comment]
@MatthewPennock , thank you for testing and reporting back!
