### PR TITLE
[otns] fix simulation to use strong otPlatOtnsStatus definition

### LINKED ISSUE #5170: [github-actions] cli-ftd-otns failing in master
**Describe the bug** A clear and concise description of what the bug is.

cli-ftd-otns GitHub Action is failing in master

**To Reproduce** Information to reproduce the behavior, including:

1. Git commit id: 5ce4046
2. IEEE 802.15.4 hardware platform: N/A
3. Build steps: N/A
4. Network topology: N/A

**Expected behavior** A clear and concise description of what you expected to happen.

cli-ftd-otns GitHub Action passes.

**Console/log output** If applicable, add console/log output to help explain your problem.

https://github.com/openthread/openthread/runs/824271448

[logs_9382.zip](https://github.com/openthread/openthread/files/4854580/logs_9382.zip)

**Additional context** Add any other context about the problem here.

Started failing after merging #5155

### PR DESCRIPTION
**Pull request by simonlingoogle**
This PR fixes #5170 

This PR also fixes the issue that OTNS tests failed to use openthread of the current PR, but used openthread master instead. 

@ctan-g could you verify if this fix works for Silk?

### CODE REVIEW

File: examples/platforms/utils/otns_utils.cpp [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+#include <openthread/config.h>
+
+#include <openthread/platform/otns.h>
+#include <openthread/platform/toolchain.h>
+
+#include "common/logging.hpp"
+
+/*
+ * Implementation note:
+ *   These are all "weak" so that a platform may if it chooses  override the instance.
```
Comment (ctan-g) [inline examples/platforms/utils/otns_utils.cpp:38]: Looks like an extra space after "chooses".

**Comment by simonlingoogle** [comment]
> I am just curios, what was the issue with strong definition not being linked.

I am not clear why the `weak` definition is used. 
Actually if both definitions are strong, it still compiles without any complain. 
I suspect that the linker just found the first definition for the symbol and stopped searching any more even though the definition was weak. 
[Some](https://stackoverflow.com/a/13100465) say that `weak` symbols should be defined in libraries to be effective, which is consistent with what we have seen. 
@abtink @ctan-g
