### PR TITLE
[cli] fix router table command

### LINKED ISSUE #2709: Recent commits haven't been backward compatibility since #2667
SUMMARY

Recent commits could not join one same WPAN with previous since #2667 ;
Sniffer with previous version could not decrypt packets from nodes using recent firmware
Platform: Nordic

DETAILS

Nodes with 2649 and Node with 2684 could not join one same OT network with the proper configuration.
This difference should happen since #2667 (2667. could not co-work with 2666, 2666. is working with previous versions)
Use sniffer to debug, sniffer (older version than 2666.) could not decrypt packets after 2667. (including MLE and UDP, while the same sniffer could decrypt packet before 2667 well)

### PR DESCRIPTION
**Pull request by jwhui**
Resolves #2709.

### CODE REVIEW

File: src/cli/cli.cpp [hunk 1]
```diff
@@ -2348,40 +2350,41 @@ void Interpreter::ProcessRouter(int argc, char *argv[])
                 "+----+--------+----------+-----------+-------+--------+-----+------------------+\r\n");
         }
 
-        for (uint8_t i = 0;; i++)
+        maxRouterId = otThreadGetMaxRouterId(mInstance);
+
+        for (uint8_t i = 0; i <= maxRouterId; i++)
         {
-            if (otThreadGetRouterInfo(mInstance, i, &routerInfo) != OT_ERROR_NONE)
+            if ((otThreadGetRouterInfo(mInstance, i, &routerInfo) != OT_ERROR_NONE) || !routerInfo.mAllocated)
```
Comment (librasungirl) [inline src/cli/cli.cpp]: Is `!routerInfo.mAllocated` necessary here? As in https://github.com/openthread/openthread/blob/master/src/core/thread/router_table.cpp#L458, `!routerInfo.mAllocated` would always be false if `OT_ERROR_NONE` is returned.
