### PR TITLE
[mesh-forwarder] fix link layer address selection algorithm

### LINKED ISSUE #2046: [MeshForwarder] Incorrect link-layer address selection
I found that there are couple violations to Thread Specification when it comes to link-layer address selection (in `MeshForwarder::UpdateIp6Route`).

Hightlights:
 - REED sends both link-local and real-local scope multicast message using IEEE 802.15.4 broadcast, however it must transmit message as IEEE 802.15.4 unicast to its parent.
 - When End Device sends realm-local scope multicast (e.g. from RLOC as a source) it uses extended mac addresses on IEEE 802.15.4 while short would be more efficient.
 - `UpdateIp6Route` performs link-layer address selection based on FTD or MTD type of the node, while in some situations this should be done based on current role (Router or End Device - root cause for 1).

I am going to propose some fixes for this issues.

### PR DESCRIPTION
**Pull request by LuDuda**
This PR fixes #2046.

Now multicasts messages are sent differently by End Devices and Routers.

btw. I was not able to reproduce the point 2 which i have reported (#2046) (i could wrongly identified it).

### CODE REVIEW

File: src/core/thread/mesh_forwarder.cpp [hunk 1]
```diff
@@ -754,163 +754,149 @@ otError MeshForwarder::UpdateIp6Route(Message &aMessage)
...
             GetMacDestinationAddress(ip6Header.GetDestination(), mMacDest);
-            GetMacSourceAddress(ip6Header.GetSource(), mMacSource);
         }
         else
         {
             ExitNow(error = OT_ERROR_DROP);
         }
 
-        break;
+        ExitNow();
```
Comment (LuDuda) [inline src/core/thread/mesh_forwarder.cpp]: In order to not create more "if indentations" i decided to exit from this function here.

If its more clear I can move this ExitNow(); statement from here to line 768, and even change it to ExitNow(error = OT_ERROR_NONE) to be more explicit. Thoughts?

File: src/core/thread/mesh_forwarder.cpp [hunk 2]
```diff
@@ -754,163 +754,149 @@ otError MeshForwarder::UpdateIp6Route(Message &aMessage)
...
     aMessage.Read(0, sizeof(ip6Header), &ip6Header);
 
-    switch (netif.GetMle().GetRole())
+    VerifyOrExit(!ip6Header.GetSource().IsMulticast(), error = OT_ERROR_DROP);
+
+    // 1. Choose correct MAC Source Address.
+    GetMacSourceAddress(ip6Header.GetSource(), mMacSource);
+
+    // 2. Choose correct MAC Destination Address.
+    if (netif.GetMle().GetRole() < OT_DEVICE_ROLE_CHILD)
```
Comment (bukepo) [inline src/core/thread/mesh_forwarder.cpp]: Is it more clear to name roles? Comparing between values of device roles seems a little bit strange.

File: src/core/thread/mesh_forwarder.cpp (hunk 1 above)
Comment (bukepo) [inline src/core/thread/mesh_forwarder.cpp]: Is it clearer to merge them into one as @librasungirl suggests? I think that indicates `if (netif.GetMle().GetRole() < OT_DEVICE_ROLE_CHILD`, the processing should end in this if body.

Comment (LuDuda) [inline src/core/thread/mesh_forwarder.cpp]: Ahh okay, i misunderstood the comment :+1: ! Fixed! Thanks!

File: src/core/thread/mesh_forwarder.cpp [hunk 3]
```diff
@@ -754,163 +754,150 @@ otError MeshForwarder::UpdateIp6Route(Message &aMessage)
...
+        else
+        {
+            mMacDest.mShortAddress = Mac::kShortAddrBroadcast;
+        }
+    }
+    else if (ip6Header.GetDestination().IsLinkLocal())
+    {
+        GetMacDestinationAddress(ip6Header.GetDestination(), mMacDest);
+    }
+    else
```
Comment (jwhui) [inline src/core/thread/mesh_forwarder.cpp]: Merge the first if-statement below into this line, to avoid additional nesting?

File: src/core/thread/mesh_forwarder.cpp [hunk 4]
```diff
@@ -754,163 +754,150 @@ otError MeshForwarder::UpdateIp6Route(Message &aMessage)
...
-            }
-            else
-            {
-                ExitNow(error = OT_ERROR_DROP);
-            }
+            mMacDest.mLength       = sizeof(mMacDest.mShortAddress);
+            mMacDest.mShortAddress = netif.GetMle().GetNextHop(Mac::kShortAddrBroadcast);
         }
 
 #if OPENTHREAD_FTD
```
Comment (jwhui) [inline src/core/thread/mesh_forwarder.cpp]: Add an `#else` to assert if we are here and `IsMinimalEndDevice()` returns `false`?

**Comment by LuDuda** [comment]
I addressed comments and rebased to the master.
