### PR TITLE
[posix] fix build warnings/errors on macOS

### LINKED ISSUE #5133: posix DAEMON=1 build failed on macOS
**Describe the bug**
Build on macOS failed with DAEMON=1.

**To Reproduce**

1. Git commit id: 0cf84da1006d70ac0a3a817406d702a1132eab63
2. IEEE 802.15.4 hardware platform: macOS, posix
3. Build steps
```bash
./bootstrap
make -f src/posix/Makefile-posix DAEMON=1
```

**Expected behavior**
Build successfully.

**Console/log output**
```bash
  CXX      libopenthread_posix_a-udp.o
  CXX      libopenthread_posix_a-virtual_time.o
/Users/simonlin/src/openthread/src/posix/../../src/posix/platform/udp.cpp:86:28: error: variable length arrays are a C99 feature [-Werror,-Wvla-extension]
                    control[OT_APPLE_IGNORE_GNU_FOLDING_CONSTANT(CMSG_SPACE(sizeof(struct in6_pktinfo)) + CMSG_SPACE(sizeof(int)))];
                           ^
/Users/simonlin/src/openthread/src/posix/../../src/posix/platform/udp.cpp:113:26: error: implicit conversion loses integer precision: 'unsigned long' to 'socklen_t' (aka 'unsigned int')
      [-Werror,-Wshorten-64-to-32]
    msg.msg_controllen = sizeof(control);
                       ~ ^~~~~~~~~~~~~~~
2 errors generated.
```

### PR DESCRIPTION
**Pull request by bukepo**
fixes #5133

### CODE REVIEW

File: src/posix/platform/udp.cpp [hunk 1]
```diff
@@ -79,15 +79,19 @@ static bool IsMulticast(const otIp6Address &aAddress)
 
 static otError transmitPacket(int aFd, uint8_t *aPayload, uint16_t aLength, const otMessageInfo &aMessageInfo)
 {
+#ifdef __APPLE__
+    constexpr size_t kBufferSize = 128;
```
Comment (simonlingoogle) [inline src/posix/platform/udp.cpp:83]: Is it possible to use some `sizeof(xxx)` ?

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:
with a question

File: src/posix/platform/udp.cpp [hunk 2]
```diff
@@ -149,7 +153,7 @@ static otError transmitPacket(int aFd, uint8_t *aPayload, uint16_t aLength, cons
 #ifdef __APPLE__
     msg.msg_controllen = static_cast<socklen_t>(controlLength);
 #else
-    msg.msg_controllen = controlLength;
+    msg.msg_controllen           = controlLength;
```
Comment (Irving-cl) [inline src/posix/platform/udp.cpp:156]: align?

**Review by Irving-cl — APPROVED** [review]
LGTM :+1:

Fix the align?

File: src/posix/platform/udp.cpp (hunk 1 above)
Comment (bukepo) [reply src/posix/platform/udp.cpp:83]: I don't know what xxx is.

Comment (rob-the-dude) [reply src/posix/platform/udp.cpp:83]: I think Simon is doesn't like that, on mac OS, we're using a magic number (128) where on other platforms, you're using some macros that explain how big the buffer is (CMSG_SPACE of particular structures).  If I understand, the reason you're doing it this way is because mac OS generates a warning/error about the expression supplied?  Maybe a comment that says why we have to do it this way on mac OS?  Or did I not understand the change?

Comment (simonlingoogle) [reply src/posix/platform/udp.cpp:83]: Agree that at least a comment is needed.

File: src/posix/platform/udp.cpp (hunk 2 above)
Comment (bukepo) [reply src/posix/platform/udp.cpp:156]: it's already the result of clang-format.

**Review by jwhui — APPROVED** [review]
