### PR TITLE
[spinel] use local variables to export mac key before sending over SPINEL

### LINKED ISSUE #9515: [crypo] build fails when `PLATFORM_KEY_REFERENCES_ENABLE` set to `1`
**Describe the bug**

Build fails when `OPENTHREAD_CONFIG_PLATFORM_KEY_REFERENCES_ENABLE` is set to `1`.

Issue is converting a `const` to a `non-const`:

https://github.com/openthread/openthread/blob/57ef721eeed2550835c528ab7b8e77671f7039d6/src/lib/spinel/radio_spinel.cpp#L893-L898

**To Reproduce**

1. Git commit id 7568e31c0831fcf90fdbe40680f82dc462bde33f
2. IEEE 802.15.4 hardware platform EFR32
3. Build steps https://github.com/openthread/ot-efr32/actions/runs/6478948918/job/17591559259?pr=703
4. Network topology N/A

**Expected behavior**

Build checks should succeed.

**Console/log output**

From:

```
In file included from /__w/ot-efr32/ot-efr32/openthread/src/core/common/data.hpp:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_types.hpp:47,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_frame.hpp:45,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/radio.hpp:46,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/max_power_table.hpp:32,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:40,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp: In member function 'otError ot::Spinel::RadioSpinel::SetMacKey(uint8_t, uint8_t, const otMacKeyMaterial*, const otMacKeyMaterial*, const otMacKeyMaterial*)':
/__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:893:109: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     SuccessOrExit(error = otPlatCryptoExportKey(aPrevKey->mKeyMaterial.mKeyRef, aPrevKey->mKeyMaterial.mKey.m8,
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/__w/ot-efr32/ot-efr32/openthread/src/core/common/code_utils.hpp:107:14: note: in definition of macro 'SuccessOrExit'
         if ((aStatus) != 0)    \
              ^~~~~~~
In file included from /__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/radio.h:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:37,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/crypto.h:284:9: note:   initializing argument 2 of 'otError otPlatCryptoExportKey(otCryptoKeyRef, uint8_t*, size_t, size_t*)'
 otError otPlatCryptoExportKey(otCryptoKeyRef aKeyRef, uint8_t *aBuffer, size_t aBufferLen, size_t *aKeyLen);
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /__w/ot-efr32/ot-efr32/openthread/src/core/common/data.hpp:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_types.hpp:47,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_frame.hpp:45,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/radio.hpp:46,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/max_power_table.hpp:32,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:40,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:895:109: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     SuccessOrExit(error = otPlatCryptoExportKey(aCurrKey->mKeyMaterial.mKeyRef, aCurrKey->mKeyMaterial.mKey.m8,
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/__w/ot-efr32/ot-efr32/openthread/src/core/common/code_utils.hpp:107:14: note: in definition of macro 'SuccessOrExit'
         if ((aStatus) != 0)    \
              ^~~~~~~
In file included from /__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/radio.h:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:37,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/crypto.h:284:9: note:   initializing argument 2 of 'otError otPlatCryptoExportKey(otCryptoKeyRef, uint8_t*, size_t, size_t*)'
 otError otPlatCryptoExportKey(otCryptoKeyRef aKeyRef, uint8_t *aBuffer, size_t aBufferLen, size_t *aKeyLen);
         ^~~~~~~~~~~~~~~~~~~~~
In file included from /__w/ot-efr32/ot-efr32/openthread/src/core/common/data.hpp:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_types.hpp:47,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/mac/mac_frame.hpp:45,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/radio.hpp:46,
                 from /__w/ot-efr32/ot-efr32/openthread/src/core/radio/max_power_table.hpp:32,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:40,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:897:109: error: invalid conversion from 'const uint8_t* {aka const unsigned char*}' to 'uint8_t* {aka unsigned char*}' [-fpermissive]
     SuccessOrExit(error = otPlatCryptoExportKey(aNextKey->mKeyMaterial.mKeyRef, aNextKey->mKeyMaterial.mKey.m8,
                                                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
/__w/ot-efr32/ot-efr32/openthread/src/core/common/code_utils.hpp:107:14: note: in definition of macro 'SuccessOrExit'
         if ((aStatus) != 0)    \
              ^~~~~~~
In file included from /__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/radio.h:43:0,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.hpp:37,
                 from /__w/ot-efr32/ot-efr32/openthread/src/lib/spinel/radio_spinel.cpp:34:
/__w/ot-efr32/ot-efr32/openthread/include/openthread/platform/crypto.h:284:9: note:   initializing argument 2 of 'otError otPlatCryptoExportKey(otCryptoKeyRef, uint8_t*, size_t, size_t*)'
 otError otPlatCryptoExportKey(otCryptoKeyRef aKeyRef, uint8_t *aBuffer, size_t aBufferLen, size_t *aKeyLen);
         ^~~~~~~~~~~~~~~~~~~~~
[495/719] Building CXX object openthread/src/core/CMakeFiles/openthread-mtd.dir/utils/slaac_address.cpp.obj
[496/719] Building C object openthread/src/lib/spinel/CMakeFiles/openthread-spinel-ncp.dir/spinel.c.obj
ninja: build stopped: subcommand failed.
```

### PR DESCRIPTION
**Pull request by hemanth-silabs**
In RadioSpinel::SetMacKey we try to reuse the otMacKey passed to export the literal key from PSA to be sent over SPINEL to RCP. But as the passed param is const, we cant really use this. Better option is to extract it into a local buffer and use that to pass the keys to RCP.

Use OT_MAC_KEY_SIZE instead of sizeof.
Simplify RCP restoration code.

Fixes #9515

### CODE REVIEW

**Comment by hemanth-silabs** [comment]
@jwhui Can you have a look?

**Review by romacdon — APPROVED** [review]
LGTM

File: src/lib/spinel/radio_spinel.cpp [hunk 1]
```diff
@@ -884,35 +884,43 @@ otError RadioSpinel::SetMacKey(uint8_t                 aKeyIdMode,
...
+    SuccessOrExit(error =
+                      otPlatCryptoExportKey(aCurrKey->mKeyMaterial.mKeyRef, currKey.m8, OT_MAC_KEY_SIZE, &aKeySize));
+    SuccessOrExit(error =
+                      otPlatCryptoExportKey(aNextKey->mKeyMaterial.mKeyRef, nextKey.m8, OT_MAC_KEY_SIZE, &aKeySize));
 #else
     OT_UNUSED_VARIABLE(aKeySize);
+
+    memcpy(prevKey.m8, aPrevKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
+    memcpy(currKey.m8, aCurrKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
+    memcpy(nextKey.m8, aNextKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
```
Comment (abtink) [inline src/lib/spinel/radio_spinel.cpp:907]: I think we can use `operator=` for structs in c++ to simplify this and following lines:
```
prevKey = aPrevKey->mKeyMaterial.mKey;
...
```

With `=`, we know that we are copying the entire struct content, and I recommend this over `memcpy()`, which has the potential for incorrect use if the passed-in size argument is not correct

File: src/lib/spinel/radio_spinel.cpp [hunk 2]
```diff
@@ -884,35 +884,43 @@ otError RadioSpinel::SetMacKey(uint8_t                 aKeyIdMode,
...
 #if OPENTHREAD_SPINEL_CONFIG_RCP_RESTORATION_MAX_COUNT > 0
     mKeyIdMode = aKeyIdMode;
     mKeyId     = aKeyId;
-    memcpy(mPrevKey.m8, aPrevKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
-    memcpy(mCurrKey.m8, aCurrKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
-    memcpy(mNextKey.m8, aNextKey->mKeyMaterial.mKey.m8, OT_MAC_KEY_SIZE);
+
+    memcpy(mPrevKey.m8, prevKey.m8, OT_MAC_KEY_SIZE);
+    memcpy(mCurrKey.m8, currKey.m8, OT_MAC_KEY_SIZE);
+    memcpy(mNextKey.m8, nextKey.m8, OT_MAC_KEY_SIZE);
```
Comment (abtink) [inline src/lib/spinel/radio_spinel.cpp:922]: Same here, can use `=`?

Comment (hemanth-silabs) [reply src/lib/spinel/radio_spinel.cpp]: Good point. Updated the implementation.

**Review by abtink — APPROVED** [review]
LGTM. Thanks.

**Review by jwhui — APPROVED** [review]
