### PR TITLE
[efr32] update to RAIL 2.x

### LINKED ISSUE #2372: STATUS_NOMEM on SiLabs EFR32
Hi there,

I've been testing SiLabs MGM12P modules with OpenThread. After a 30min to 2 hours of operation the NCP stops transmitting/receiving IPv6 packets. On every transmit wpantund tells me that NCPs last status is STATUS_NOMEM.

```
Nov 27 23:35:49  wpantund[399]: Tickle...
Nov 27 23:35:49  wpantund[399]: [->NCP] CMD_NOOP tid:7
Nov 27 23:35:49  wpantund[399]: [NCP->] CMD_PROP_VALUE_IS(PROP_LAST_STATUS) tid:7
Nov 27 23:35:49  wpantund[399]: [-NCP-]: Last status (STATUS_OK, 0)
Nov 27 23:35:51  wpantund[399]: [->NCP] IPv6 len:115 type:17(cksum 0xa257) [SECURE]
Nov 27 23:35:51  wpantund[399]:         to(remote):[ff03::1]:4000
Nov 27 23:35:51  wpantund[399]:         from(local):[fd41:4d42:4552:0:4ee:14d0:6710:a5c5]:56943
Nov 27 23:35:56  wpantund[399]: [->NCP] IPv6 len:115 type:17(cksum 0x19f2) [SECURE]
Nov 27 23:35:56  wpantund[399]:         to(remote):[ff03::1]:4000
Nov 27 23:35:56  wpantund[399]:         from(local):[fd41:4d42:4552:0:4ee:14d0:6710:a5c5]:56943
Nov 27 23:35:56  wpantund[399]: [NCP->] CMD_PROP_VALUE_IS(PROP_LAST_STATUS) tid:0
Nov 27 23:35:56  wpantund[399]: [-NCP-]: Last status (STATUS_NOMEM, 11)
Nov 27 23:36:01  wpantund[399]: [->NCP] IPv6 len:115 type:17(cksum 0xda92) [SECURE]
```

Has anyone else encountered this before?

What's the best way to debug this when it takes several hours to reproduce?

### LINKED ISSUE #2379: efr32 CSMA done twice?
It seems that both the radio and OpenThread perform CSMA.

In efr32 radio.c function otPlatRadioTransmit
```
RAIL_CsmaConfig_t csmaConfig = RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA;
...
railTxStatus = RAIL_TxStartWithOptions(aFrame->mChannel, &txOption, RAIL_CcaCsma, &csmaConfig);
```

RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA is

```
/**
 * @def RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA
 * @brief RAIL_CsmaConfig_t initializer configuring CSMA per 802.15.4-2003
 * on 2.4 GHz OSPSK, commonly used by ZigBee.
 */
#define RAIL_CSMA_CONFIG_802_15_4_2003_2p4_GHz_OQPSK_CSMA {                    \
    /* CSMA per 802.15.4-2003 on 2.4 GHz OSPSK, commonly used by ZigBee     */ \
    /* csmaMinBoExp */ 3,   /* 2^3-1 for 0..7 backoffs on 1st try           */ \
    /* csmaMaxBoExp */ 5,   /* 2^5-1 for 0..31 backoffs on 3rd+ tries       */ \
    /* csmaTries    */ 5,   /* 5 tries overall (4 re-tries)                 */ \
    /* ccaThreshold */ -75, /* 10 dB above sensitivity                      */ \
    /* ccaBackoff   */ 320, /* 20 symbols at 16 us/symbol                   */ \
    /* ccaDuration  */ 128, /* 8 symbols at 16 us/symbol                    */ \
    /* csmaTimeout  */ 0,   /* no timeout                                   */ \
}
```

so SiLabs Rail is set to use CSMA.

Now if we look into MAC layer, we see that before transmitting it calls `RadioSupportsCsmaBackoff()` and if it returns false - performs its own CSMA. In efr32 radio.c function, otPlatRadioGetCaps doesn't set OT_RADIO_CAPS_TRANSMIT_RETRIES or OT_RADIO_CAPS_CSMA_BACKOFF bits so this is precisely what happens.

### PR DESCRIPTION
**Pull request by jwhui**
This update also makes the following changes:
- Initialize chip using `halInitChipSpecific()` provided by RAIL HAL.
- Use `RAIL_HoldRxPacket()` to move rx processing out of interrupt context
- Eliminate critical sections from `otPlatRadio*` APIs.
- Use UART driver provided by Gecko SDK.

Resolves #2372
Resolves #2379

//cc @tomas-c @plasticchris @xiaom-GitHub

### CODE REVIEW

**Comment by jwhui** [comment]
@tomas-c, this seems to be working pretty well for me in my limited testing.  Would you like to test it out?

**Comment by tomas-c** [comment]
@jwhui Ahh nice, had been thinking of doing the switch to Rail 2 and the UART driver too. Will test.

File: examples/platforms/efr32/rail_config.h [hunk 1]
```diff
@@ -0,0 +1,9 @@
+#ifndef __RAIL_CONFIG_H__
+#define __RAIL_CONFIG_H__
+
+#include <stdint.h>
+#include "rail_types.h"
+
+#define RADIO_CONFIG_XTAL_FREQUENCY 38400000UL
```
Comment (xiaom-GitHub) [inline examples/platforms/efr32/rail_config.h]: Thanks for updating to RAIL 2.0 👍 . Please remove duplicated RADIO_CONFIG_XTAL_FREQUENCY and other parameters from openthread-core-efr32-config.h if we put auto-generated header file here.

Comment (jwhui) [reply examples/platforms/efr32/rail_config.h]: Thanks!  Updated.

File: examples/platforms/efr32/uart.c [hunk 2]
```diff
@@ -39,97 +39,89 @@
...
+    sReceiveFifo.mHead = 0;
+    sReceiveFifo.mTail = 0;
 
-    /* Finally enable it */
-    USART_Enable(usart, usartEnable);
+    UARTDRV_Init(sUartHandle, &uartInit);
 
-    return OT_ERROR_NONE;
-}
+    UARTDRV_TransmitB(sUartHandle, (uint8_t *) "\nOpenThread\n", 12u);
```
Comment (al1img) [inline examples/platforms/efr32/uart.c]: Is this line really needed? Other platforms send nothing on otPlatUartEnable.

File: examples/platforms/efr32/uart.c [hunk 3]
```diff
@@ -153,35 +145,32 @@ otError otPlatUartSend(const uint8_t *aBuf, uint16_t aBufLength)
...
 
 void processTransmit(void)
 {
     otEXPECT(sTransmitBuffer != NULL);
 
-    for (; sTransmitLength > 0; sTransmitLength--)
-    {
-        USART_Tx(USART0, *sTransmitBuffer++);
-    }
+    UARTDRV_TransmitB(sUartHandle, (uint8_t *)sTransmitBuffer, sTransmitLength);
```
Comment (al1img) [inline examples/platforms/efr32/uart.c]: Why not use non blocking UARTDRV_Transmit? As I see OT is not designed to be blocked in process drivers call. I think sending big buffer may introduce RF packet drops etc. I notice some issue with EFR32 in case intensive data exchange and sending logs via uart. It looks like the root cause was delay in processTransmit but I didn't investigate it so much.

File: examples/platforms/efr32/radio.c [hunk 4]
```diff
@@ -361,13 +369,13 @@ otRadioFrame *otPlatRadioGetTransmitBuffer(otInstance *aInstance)
...
     (void)aInstance;
-    return (uint8_t)(RAIL_RxGetRSSI() >> 2);
+    return (int8_t)(RAIL_GetAverageRssi(sRailHandle) >> 2);
 }
 
 otRadioCaps otPlatRadioGetCaps(otInstance *aInstance)
 {
     (void)aInstance;
-    return OT_RADIO_CAPS_ACK_TIMEOUT;
+    return OT_RADIO_CAPS_ACK_TIMEOUT | OT_RADIO_CAPS_CSMA_BACKOFF;
```
Comment (al1img) [inline examples/platforms/efr32/radio.c]: Shall OT_RADIO_CAPS_TRANSMIT_RETRIES be added as well?

File: examples/platforms/efr32/uart.c (hunk 2 above)
Comment (jwhui) [reply examples/platforms/efr32/uart.c]: This was left over from my own testing.  Removed!

File: examples/platforms/efr32/uart.c (hunk 3 above)
Comment (jwhui) [reply examples/platforms/efr32/uart.c]: I'll switch this to non-blocking soon.

File: examples/platforms/efr32/radio.c (hunk 4 above)
Comment (jwhui) [reply examples/platforms/efr32/radio.c]: Does RAIL implement automatic retransmissions on no ack?

Comment (al1img) [reply examples/platforms/efr32/radio.c]: I didn't find any info about retransmissions. So, most probably doesn't implement.

File: examples/platforms/efr32/uart.c (hunk 3 above)
Comment (jwhui) [reply examples/platforms/efr32/uart.c]: Updated to use non-blocking `UARTDRV_Transmit`.

**Comment by tomas-c** [comment]
Tested CLI app (used the latest update with async UART). All basic tests mentioned in the [porting guide](https://openthread.io/guides/porting/validate_the_port) pass. Will soon check with wpantund and a bigger network of devices.

**Comment by tomas-c** [comment]
Doesn't work in NCP mode. 

Tested with wpantund versions 2d17277f1c5104ec0c6f50eabd1047a054ca54a5 and 120ef3e004f2a6df1a960191440436d9ba78fa81.

wpantund logs:

```
wpantund[2238]: Starting wpantund 0.08.00d (Dec 15 2017 18:27:47) . . .
wpantund[2238]: 	SOURCE_VERSION = 0.07.01-169-g2d17277-dirty
wpantund[2238]: Configuration file "/etc/wpantund.conf" read.
wpantund[2238]: set-config-param: "Daemon:SyslogMask" set succeded
wpantund[2238]: Stat (autolog): Tx: 0 packets (0 udp, 0 tcp, 0 icmp6) -- 0 bytes
wpantund[2238]: Stat (autolog): Tx history is empty
wpantund[2238]: Stat (autolog): 
wpantund[2238]: Stat (autolog): Rx: 0 packets (0 udp, 0 tcp, 0 icmp6) -- 0 bytes
wpantund[2238]: Stat (autolog): Rx history is empty
wpantund[2238]: Stat (autolog): 
wpantund[2238]: Stat (autolog): NCP state history is empty.
wpantund[2238]: Stat (autolog): 
wpantund[2238]: Stat (autolog): 
wpantund[2238]: Opening tun interface socket with name "tun1"
wpantund[2238]: Getting DBus connection
wpantund[2238]: Registering DBus connection
wpantund[2238]: Requesting DBus connection name com.nestlabs.WPANTunnelDriver
wpantund[2238]: Ready. Using DBUS bus ":1.297"
wpantund[2238]: Running as root without dropping privileges!
wpantund[2238]: Initializing NCP
wpantund[2238]: Removing all NCP originated addresses
wpantund[2238]: NCP is now BUSY.
wpantund[2238]: [->NCP] CMD_PROP_VALUE_GET(PROP_PROTOCOL_VERSION) tid:1
wpantund[2238]: ../../../git/src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp:412: Requirement Failed (IS_EVENT_FROM_NCP(event) && GetInstance(this)->mInboundHeader == mLastHeader)
wpantund[2238]: Resetting and trying again... (retry 1)
wpantund[2238]: [->NCP] CMD_RESET tid:2
wpantund[2238]: ../../../git/src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[2238]: Resetting and trying again... (retry 2)
wpantund[2238]: SuperSocket::reset()
wpantund[2238]: ../../../git/src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[2238]: Resetting and trying again... (retry 3)
wpantund[2238]: [->NCP] CMD_RESET tid:3
wpantund[2238]: ../../../git/src/ncp-spinel/SpinelNCPInstance-Protothreads.cpp:402: Requirement Failed (event == EVENT_NCP_RESET)
wpantund[2238]: The NCP is misbehaving: Repeatedly unable to initialize NCP. Entering fault state.
wpantund[2238]: State change: "uninitialized" -> "uninitialized:fault"
wpantund[2238]: DBus Sending Interface Added Signal for tun1
```

**Comment by tomas-c** [comment]
This pull request seems to fix issue #2372.

Not sure if this was an issue with old RAIL implementation (couldn't test due to #2372) but I have noticed the network is much less stable than with SiLabs Thread v2.3.1.0 stack.

Had four devices continuously sending messages to each other. With SiLabs stack I didn't have single missed message over 12 hour period. 

With OpenThread I had hundreds of missed messaged over the same period with the same setup (same CCA threshold, same transmit power, same channel).

**Comment by jwhui** [comment]
@tomas-c, thanks for testing and providing feedback!  I found a bug in handling RAIL's received packet FIFO.  In particular, packets that were in process of being received could be discarded by the example driver.  I have updated the example driver to avoid this.  When you get a chance, try out the latest and let me know if you see improvement.

**Comment by tomas-c** [comment]
@jwhui Good catch! Been running for three hours already and no lost messages so far.

**Comment by jwhui** [comment]
@tomas-c, great to hear!

File: examples/platforms/efr32/uart.c [hunk 5]
```diff
@@ -39,155 +39,145 @@
...
+#define USART_INIT                                                                           \
+    {                                                                                        \
+        RETARGET_UART,                                    /* USART port */                   \
+        115200,                                           /* Baud rate */                    \
+        RETARGET_TX_LOCATION,                             /* USART Tx pin location number */ \
+        RETARGET_RX_LOCATION,                             /* USART Rx pin location number */ \
+        (USART_Stopbits_TypeDef)USART_FRAME_STOPBITS_ONE, /* Stop bits */                    \
+        (USART_Parity_TypeDef)USART_FRAME_PARITY_NONE,    /* Parity */                       \
+        (USART_OVS_TypeDef)USART_CTRL_OVS_X16,            /* Oversampling mode*/             \
+        false,                                            /* Majority vote disable */        \
```
Comment (tomas-c) [inline examples/platforms/efr32/uart.c]: Spinel docs say flow control must be used. I had framing errors at higher baud rates if it's not enabled.

Tested and works if:

- Change `uartdrvFlowControlNone` to `uartdrvFlowControlHwUart`
- Change `0,0` at the end of this struct to `RETARGET_CTS_LOCATION, RETARGET_RTS_LOCATION`

File: examples/platforms/efr32/uart.c [hunk 6]
```diff
@@ -39,155 +39,145 @@
...
+
+otError otPlatUartSend(const uint8_t *aBuf, uint16_t aBufLength)
+{
+    otError error = OT_ERROR_NONE;
+
+    otEXPECT_ACTION(sTransmitBuffer == NULL, error = OT_ERROR_BUSY);
+
+    sTransmitBuffer = aBuf;
+    sTransmitLength = aBufLength;
+
```
Comment (tomas-c) [inline examples/platforms/efr32/uart.c]: Given UARTDRV_Transmit is asynchronous and aBuf can be reclaimed after otPlatUartSend returns, we should copy aBuf contents, not just its pointer.

Comment (tomas-c) [reply examples/platforms/efr32/uart.c]: Ah, just saw that layer above makes sure the buffer is not touched until this is done. Disregard.

File: examples/platforms/efr32/uart.c (hunk 5 above)
Comment (jwhui) [reply examples/platforms/efr32/uart.c]: @tomas-c, thanks!  I updated this PR with your proposed changes.

**Comment by tomas-c** [comment]
I got the system to run for 36h without any issues, with
- latest code from this PR
- 115200 baud rate
- hardware flow control
- all NCP logging disabled
- OPENTHREAD_CONFIG_NCP_TX_BUFFER_SIZE increased to 4096
- OPENTHREAD_CONFIG_NCP_UART_TX_CHUNK_SIZE increased to 512
- uart.c modified to use a 256 byte ring buffer being serviced by two UARTDRV_Receive() calls in 32 byte chunks

It's difficult to tell at this point which of these were necessary (will not have time to investigate for a while) but might be that the latest changes from this PR and default settings are enough to get a stable network with EFR32.

**Comment by jwhui** [comment]
@tomas-c, thanks for the feedback again!  Do you think this PR is good for merge?  If we find more issues, we can address them in subsequent PRs.

**Comment by tomas-c** [comment]
This seems to work better than the current Rail 1.x based version and I can't think of any improvements besides maybe increasing UART RX DMA buffer size to something bigger than 1 byte but it's tricky and should probably come as a separate PR.

I'd say let's merge this!

**Comment by erbp** [comment]
@tomas-c I'm new to openThread, but have built this version for my efr32 dev boards and was wondering how you were testing the stability?  You mentioned test sending messages between nodes, was this UDP messages?  Do you have a test app that is not included in this repository to do this?  I wanted to test sending messages between my dev boards over the thread network, but wasn't sure how to go about this easily.

Thanks.

**Comment by tomas-c** [comment]
@erbp If you just want to test whether sending messages works - you can probably just follow the platform readme file and use the ping command. You can also follow the [CLI app example](https://openthread.io/guides/building/commissioning) or a more involved [CLI app + NCP example](https://codelabs.developers.google.com/codelabs/openthread-hardware/). 

I myself use a bunch of Linux devices running wpantund with NCPs connected to them. I have an existing setup with SiLabs Thread stack so just switched it out with OpenThread to test. Can't really share it but on Linux with wpantund you can write a simple Python script to send UDP packets or even use CoAP. 

As for how to send UDP messages directly from the devices without wpantund - someone else might be more equiped to point you in the right direction.

**Comment by jwhui** [comment]
@tomas-c, thanks for your help on this PR!
