### PR TITLE
#1599 - Update examples/platform/posix/flash.c for speed/memory reasons

### LINKED ISSUE #1599: examples/posix/flash.c problems with self-checks.
Technically there is nothing wrong with this, but depending upon the machine validation check-tests run on, the tests fail.  The current result, depending on the environment where the self-test operations are run they fail - randomly, but run perfectly when the next time.

The intent here is to fix/address the problem so that the validation tests work on more machines.

During the FLASH.C init() call, the simulated flash is erased - the current configuration is a simulated 256K byte flash chip (page size: 0x800(2K), npages=128 = 256K) 

Underlying problem:  The ${openthread}/tests/scripts/thread-cert directory - is run with numerous test scripts in parallel.  For example  Cert_5_2_06_RouterDowngrade.py - launches 26 instances of the CLI, Cert-5_2_03_LeaderReject2Hops.py launches 33 instances - the point here is there is a huge number of instances of the CLI application running in parallel.

The above to factors together cause the errors.

Solution/Option that is rejected:  Changing theses tests to run in *SEQUENCE* (not parallel) takes, means some tests take more then 3 hours to complete on the Travis-CI servers, well beyond a reasonable time limit. In fact, Travis dies with timeout errors.

Solution/Option that is rejected: Adjusting the total number of parallel jobs may solve the solution for one environment, but not all test environments, and extend test time on fast machines.

Solution/Option that is rejected: Just use a Bigger/Faster machines, this solution may work on sever class machine, but it is better if all developers can run the complete test suite on their assigned laptop, which may for example actually use a virtual machine. The developer tells the boss: I need a new laptop, the biggest, the baddest, the fastest thing on the planet.  The Boss says: What are you smoking?

Problem Detail 1 - The current implementation of page erase writes single bytes by calling pwrite()

Thus there are 50 instances of the CLI app - making 256K calls to the pwrite() function, each writing a single byte - depending upon the load on the machine running the test  (typically a VM of some sort) things timeout and fail for random reasons.

The solution is in this function *write* full pages in one operation, obviously (PAGE SIZE) 2048 times faster.

Problem Detail 2 - which is more of a comment of how *NOT* to fix this, and not cause other problems.  I learned this during my attempt to resolve the above issue.

To accomplish 1 (full page writes) - we need a PAGESIZE array of bytes, this could be: STATIC allocation,  MALLOC allocation, or on the runtime stack.

Static is not always a good solution.

The way to *NOT* solve this is to use MALLOC, meaning:  Allocate a page, initialize the page to 0xff, write the page, then free the page.

here's why:  Some (not all) of the tests make use of the address sanitizer  (aka: libasan, or just ASAN) the address sanitizer has a feature to detect  use-memory-after-free. To accomplish this, the function free() is changed to *NEVER* release the memory, instead free() "poisons" the freed memory in some form but does not release the memory. The net effect, the ASAN feature becomes a rather massively large memory leak.

Part 1: Thus any application that makes *MANY* malloc/free calls will cause a huge pseudo-memory leak. The CLI applications do exactly this as part of the flash page erase operation.

Part 2: Because the CERT tests execute well more then 50 tests in parallel, each with their own "pseudo-massive-memory-leak" means the test machine requires a HUGE amount of RAM (or swap space) this, coupled with virtual memory paging often results in either (a) timeout failures, (b) random strange crashes in Python due to out of memory errors, or (c) random failures in the ASAN enabled tests due to allocation failures.

On travis-ci, if you run the test second, or third time it sometimes passes, but another combination of tests fail, what is generally consistent is exactly an "out-of-memory" error/failure due to malloc/free + ASAN.

The simple solution is, in this case to place the dummy page on the runtime stack,  and not use malloc/free, and not use static memory allocation.

### PR DESCRIPTION
**Pull request by DuaneEllis-TI**
Resolves #1599.

Some notes:

1.  Do not change this to a for(;;) loop that writes bytes.  This takes forever and causes timeouts to occur.
    * The math:
      *  With pagesize = 8K pages, and n-pages=128 This turns into 1 million calls to "pwrite()" Those 1million calls occur during startup. The "Thread Cert" tests, in some cases start over 30+ instances of the simulated app...
      * Tests actually run in parallel, in some cases there are 70 to 80 instances of the CLI app starting up. Each one calling write - 1 million times, writing exactly 1 byte
      * That becomes super slow. Thus we write full pages.  On a powerful platform this is fast, very fast. On a virtual machine (ie: test-build-farm) it is slow.
      * Result is: The Thread Cert tests fail/timeout

2. Do not allocate memory for the page via malloc/free.  Reason: this causes false failures in some test modes
    * Specifically when enabling the address sanitizer ... And running thread certification tests *in parallel*  The memory requirements become huge.

Background: The way "asan" works is this: When you free a page the "libasan" does not actually free the page instead libasan poisons the page but does not actually free the page, why? Because the goal to detect using the memory Thus ASAN is like a giant memory leak, it must hold onto the page so that it can detect "use-after-free"

Next (part 2)... the CERT tests, and run in parallel there are cases where 70 to 80 instances of the CLI app run in parallel - its a huge pseudo-memory leak times 70 Depending upon your machine you need 8 to 16gig of ram Virtual test boxes are often configured with much less

The solution is to use a full page on the stack it could be a static, variable however, we are running on Linux, we have plenty of RAM.

### CODE REVIEW

File: examples/platforms/posix/flash.c [hunk 1]
```diff
@@ -34,6 +34,7 @@
 #include <fcntl.h>
 #include <sys/stat.h>
 #include <string.h>
+#include <malloc.h>
```
Comment (jwhui) [inline examples/platforms/posix/flash.c]: I don't think this `#include` is needed.

File: examples/platforms/posix/flash.c [hunk 2]
```diff
@@ -98,19 +99,70 @@ uint32_t utilsFlashGetSize(void)
 ThreadError utilsFlashErasePage(uint32_t aAddress)
 {
     ThreadError error = kThreadError_None;
-    uint8_t buf = 0xff;
     uint32_t address;
+    uint8_t dummy_page[ FLASH_SIZE ];
```
Comment (jwhui) [inline examples/platforms/posix/flash.c]: nit: prefer camel case (i.e. `dummyPage`).

File: examples/platforms/posix/flash.c [hunk 3]
```diff
@@ -98,19 +99,70 @@ uint32_t utilsFlashGetSize(void)
...
     otEXPECT_ACTION(aAddress < FLASH_SIZE, error = kThreadError_InvalidArgs);
 
     // Get start address of the flash page that includes aAddress
     address = aAddress & (~(uint32_t)(FLASH_PAGE_SIZE - 1));
 
-    for (uint16_t offset = 0; offset < FLASH_PAGE_SIZE; offset++)
-    {
-        otEXPECT_ACTION(pwrite(sFlashFd, &buf, 1, address + offset) == 1, error = kThreadError_Failed);
-    }
+    // Some notes:
```
Comment (jwhui) [inline examples/platforms/posix/flash.c]: The notes below are great!  At the same time, I think this might be better placed in the commit message rather directly in the code.  I don't think there was a good reason to use the `for-loop` implementation and I can't think of a reason why someone might want to revert back to that implementation.

**Comment by DuaneEllis-TI** [comment]
Changed per request.
