### PR TITLE
Test 9.2.12 fixes

### LINKED ISSUE #1444: Test case 9.2.12 problem
When nodes listening on a channel receive MLE Announce with greater Active Timestamp and other channel, they send simultaneously Parent Request message on the other channel. It causes packet collisions. Perhaps there should be jitter when sending Parent Request in response to the Announce message.

### PR DESCRIPTION
**Pull request by hubertmis**
This PR fixes #1444 .

It adds jitter before sending Parent Request message to avoid packet collisions after receiving Announce message.

This change showed problem with attachment procedure just after parent candidate becomes Router: before candidate established route path to the Leader it did not respond to Parent Request messages. I added initial path to the Leader (when upgrading to Router state) to use previous parent as mNextHop and previous parent's cost as mCost. Using this data, parent candidate can send Parent Response. The node that upgraded to the Router state updates it's routing data when it receives Link Accept and/or Advertisement messages.

I fixed one more problem that showed: when Link was asymmetric (A has link to B but B does not have link to A) and A sent broadcast Link Request, B responded with Link Accept and Request. But A dropped this message. It should be processed and Link Accept sent in response.

### CODE REVIEW

File: src/core/thread/mle.hpp [hunk 1]
```diff
@@ -1355,6 +1355,8 @@ class Mle
 
     uint8_t mLastPartitionRouterIdSequence;
     uint32_t mLastPartitionId;
+protected:
+    uint8_t mParentLeaderCost;
```
Comment (jwhui) [inline src/core/thread/mle.hpp]: style nit: add a newline before access modifiers

File: src/core/thread/mle.cpp [hunk 2]
```diff
@@ -76,7 +76,6 @@ Mle::Mle(ThreadNetif &aThreadNetif) :
     mLastPartitionRouterIdSequence(0),
     mLastPartitionId(0),
     mParentRequestMode(kMleAttachAnyPartition),
-    mParentLinkQuality(0),
```
Comment (jwhui) [inline src/core/thread/mle.cpp]: 👍

File: src/core/thread/mle_router.cpp [hunk 3]
```diff
@@ -3821,6 +3822,18 @@ void MleRouter::HandleAddressSolicitResponse(Coap::Header *aHeader, Message *aMe
...
+    // Keep route path to the Leader reported by the parent before it is updated.
+    if (mRouters[GetLeaderId()].mCost == 0)
+    {
+        mRouters[GetLeaderId()].mCost = mParentLeaderCost;
+    }
+
+    mRouters[GetLeaderId()].mNextHop = GetRouterId(mParent.mValid.mRloc16);
+
+    // Keep link to the parent in order to response to Parent Requests before new link is established.
+    memcpy(&mRouters[GetRouterId(mParent.mValid.mRloc16)], &mParent, sizeof(mParent));
```
Comment (jwhui) [inline src/core/thread/mle_router.cpp]: nit: use assignment operator?
