### PR TITLE
[nrf528xx] don't return OT_ERROR_FAILED from otPlatRadioTransmit

### LINKED ISSUE #3726: [nrf52840] otPlatRadioTransmit() returns errors not defined in API
**Describe the bug**
OpenThread only allows returning `OT_ERROR_INVALID_STATE`, but OT_ERROR_FAILED is returned.

https://github.com/openthread/openthread/blob/master/include/openthread/platform/radio.h#L516
https://github.com/openthread/openthread/blob/master/examples/platforms/nrf52840/radio.c#L352

### PR DESCRIPTION
**Pull request by KaSroka**
otPlatRadioTransmit can return OT_ERROR_INVALID_STATE or OT_ERROR_NONE so inform about failed TX later.
This fixes #3726

### CODE REVIEW

File: examples/platforms/nrf52811/radio.c [hunk 1]
```diff
@@ -335,7 +335,7 @@ otError otPlatRadioReceive(otInstance *aInstance, uint8_t aChannel)
 
 otError otPlatRadioTransmit(otInstance *aInstance, otRadioFrame *aFrame)
 {
-    otError result = OT_ERROR_NONE;
+    bool result = true;
```
Comment (bukepo) [inline examples/platforms/nrf52811/radio.c]: It seems we should verify it's in receive state.

Comment (KaSroka) [reply examples/platforms/nrf52811/radio.c]: Our radio driver can transmit from any state so check is not needed.
