### PR TITLE
Fix polling behaviour on Thread Stop.

### LINKED ISSUE #1394: Endless MAC Poll Timer
I'm not exactly sure how I got into this state, but I think it happened when I `thread stop` and `ifconfig down` on an `otInstance`; possibly while there was an outstanding Transmit. My Windows device got into a tight loop endlessly starting a 0 ms timer:

```
09:46:46.702    [otCore]    ---> otPlatAlarmFired
09:46:46.702     [otLwf]    otPlatAlarmStop+otPlatAlarmStop
09:46:46.702    [otCore]    MAC Poll timer fired with DataRequest in SendQueue.
09:46:46.702     [otLwf]    otPlatAlarmStartAt 0 ms
09:46:46.702    [otCore]    <--- otPlatAlarmFired
09:46:46.702    [otCore]    ---> otPlatAlarmFired
09:46:46.702     [otLwf]    otPlatAlarmStop
09:46:46.702    [otCore]    MAC Poll timer fired with DataRequest in SendQueue.
09:46:46.702     [otLwf]    otPlatAlarmStartAt 0 ms
09:46:46.702    [otCore]    <--- otPlatAlarmFired
```

I don't have any other logs than these. Just 100 MB of those logs, collected in a matter of a minute. It rendered the machine completely unresponsive.

### PR DESCRIPTION
**Pull request by LuDuda**
This PR fixes #1394

### CODE REVIEW

File: src/core/thread/mesh_forwarder.cpp [hunk 1]
```diff
@@ -888,7 +901,10 @@ void MeshForwarder::SetPollPeriod(uint32_t aPeriod)
             mPollPeriod = aPeriod;
         }
 
-        mPollTimer.Start(mPollPeriod);
+        if (mPollTimer.IsRunning() && ((mNetif.GetMle().GetDeviceMode() & Mle::ModeTlv::kModeFFD) == 0))
```
Comment (abtink) [inline src/core/thread/mesh_forwarder.cpp]: I am not sure if  the `mPollTimer.IsRunning()` check is needed here. What about the case where we get here for first time and poll timer is not running, with this then the poll timer won't start...

Comment (jwhui) [inline src/core/thread/mesh_forwarder.cpp]: `SetRxOnWhenIdle()` is responsible for starting `mPollTimer`.  This change makes sure that only `SetRxOnWhenIdle()` can start `mPollTimer`.

Comment (abtink) [inline src/core/thread/mesh_forwarder.cpp]: Thanks... sounds good...
