### PR TITLE
[continuous-integration] fix test_dua_routing.py

### LINKED ISSUE #6566: [github-actions] test_dua_routing.py fails intermittently
[logs_8083.zip](https://github.com/openthread/openthread/files/6431084/logs_8083.zip)
[thread-1-2-backbone-results.zip](https://github.com/openthread/openthread/files/6431085/thread-1-2-backbone-results.zip)

### PR DESCRIPTION
**Pull request by superwhd**
This PR fixes #6566.

Added new API/CLI for reference devices to set allowed ranges of router IDs. When the allowed ID range is set, the leader will only assign router IDs in the range. In this way, we can assign non-overlapping router ID ranges to different thread networks so that no RLOC16s will collide across multiple thread networks. Hence #6566 can be fixed.

### CODE REVIEW

File: src/core/thread/mle_router.cpp [hunk 1]
```diff
@@ -228,8 +229,18 @@ Error MleRouter::BecomeLeader(void)
     partitionId = Random::NonCrypto::GetUint32();
 #endif
 
-    leaderId = IsRouterIdValid(mPreviousRouterId) ? mPreviousRouterId
-                                                  : Random::NonCrypto::GetUint8InRange(0, kMaxRouterId + 1);
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+    mRouterTable.GetAllowedRouterIdRange(&minRouterIdAllowed, &maxRouterIdAllowed);
+#endif
+    if (IsRouterIdValid(mPreviousRouterId) && minRouterIdAllowed <= mPreviousRouterId &&
```
[the remark this answers is not in the document]
Comment (simonlingoogle) [reply src/core/thread/mle_router.cpp:235]: Tend to leave the `mPreviousRouterId` logic unchanged. 

It's better not to change any Thread logic, but only change how Router IDs are allocated in the first place.

File: src/core/thread/router_table.cpp [hunk 2]
```diff
@@ -116,11 +116,20 @@ bool RouterTable::IsAllocated(uint8_t aRouterId) const
...
+    uint8_t minRouterIdAllowed = 0, maxRouterIdAllowed = Mle::kMaxRouterId;
+
+    GetAllowedRouterIdRange(&minRouterIdAllowed, &maxRouterIdAllowed);
+#endif
 
     mActiveRouterCount = 0;
 
     // build index map
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+    for (uint8_t routerId = minRouterIdAllowed; routerId <= maxRouterIdAllowed; routerId++)
```
Comment (simonlingoogle) [inline src/core/thread/router_table.cpp:129]: I think UpdateAllocation method should not be changed. `mActiveRouterCount` calculation should not be impacted by the Router ID range. 

Router indexes in `mRouters` should also be unchanged.

File: src/core/thread/router_table.cpp [hunk 3]
```diff
@@ -242,9 +264,17 @@ Router *RouterTable::Allocate(void)
...
+    uint8_t minRouterIdAllowed = 0, maxRouterIdAllowed = Mle::kMaxRouterId;
 
+    GetAllowedRouterIdRange(&minRouterIdAllowed, &maxRouterIdAllowed);
+    VerifyOrExit(minRouterIdAllowed <= aRouterId && aRouterId <= maxRouterIdAllowed &&
+                 mActiveRouterCount < Mle::kMaxRouters && !IsAllocated(aRouterId) &&
+                 mRouterIdReuseDelay[aRouterId] == 0);
+#else
     VerifyOrExit(aRouterId <= Mle::kMaxRouterId && mActiveRouterCount < Mle::kMaxRouters && !IsAllocated(aRouterId) &&
                  mRouterIdReuseDelay[aRouterId] == 0);
+#endif
```
Comment (simonlingoogle) [inline src/core/thread/router_table.cpp:281]: I think it's better to just allow allocating any Router ID to 1) minimize code change and 2) not change Thread logic.

A Thread network will never try to allocate a Router ID out of range if it was created with a given Router ID range.

File: src/core/thread/router_table.cpp [hunk 4]
```diff
@@ -202,9 +215,18 @@ Router *RouterTable::Allocate(void)
     Router *rval         = nullptr;
     uint8_t numAvailable = 0;
     uint8_t freeBit;
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
```
Comment (simonlingoogle) [inline src/core/thread/router_table.cpp:218]: `RouterTable::Allocate` change SGTM. I tend to think `RouterTable::Allocate` should be the only method that is changed in RouterTable.

**Review by simonlingoogle — COMMENTED** [review]
I believe we should limit the impact of this change:
- Better not change any non-reference-device code
- Better not change any Thread core logic
- The Router ID range should not be compulsory, but only instructive for a Thread network. For example, if a Router tries to allocate a Router ID out of range, it should be allowed (so as to not change Thread behavior). 

Thoughts? @superwhd @jwhui

File: include/openthread/thread_ftd.h [hunk 5]
```diff
@@ -739,6 +739,40 @@ void otThreadRegisterNeighborTableCallback(otInstance *aInstance, otNeighborTabl
...
+ *
+ * @note This API requires `OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE`, and is only used for test purpose. All the
+ * router IDS in the range [aMinRouterIdAllowed, aMaxRouterIdAllowed] are allowed.
+ *
+ * @param[in]  aInstance            A pointer to an OpenThread instance.
+ * @param[in]  aMinRouterIdAllowed  The minimum router ID allowed.
+ * @param[in]  aMaxRouterIdAllowed  The maximum router ID allowed.
+ *
+ * @retval  OT_ERROR_NONE           Successfully set the range.
+ * @retval  OT_ERROR_INVALID_ARGS   aMinRouterIdAllowed > aMaxRouterIdAllowed, or the range is not covered by [0, 62].
```
[the remark this answers is not in the document]
Comment (superwhd) [reply include/openthread/thread_ftd.h:768]: The max router ID is 62 instead of 63.

[the remark this answers is not in the document]
Comment (simonlingoogle) [reply include/openthread/thread_ftd.h:768]: Thanks. I forget that 63 is invalid router ID.

**Review by simonlingoogle — APPROVED** [review]
LGTM :+1:

**Comment by jwhui** [comment]
> I believe we should limit the impact of this change:
> 
> * Better not change any non-reference-device code
> * Better not change any Thread core logic
> * The Router ID range should not be compulsory, but only instructive for a Thread network. For example, if a Router tries to allocate a Router ID out of range, it should be allowed (so as to not change Thread behavior).
> 
> Thoughts? @superwhd @jwhui

I agree with the above. Thanks.

File: src/core/thread/router_table.hpp [hunk 6]
```diff
@@ -338,6 +338,27 @@ class RouterTable : public InstanceLocator, private NonCopyable
      */
     IteratorBuilder Iterate(void) { return IteratorBuilder(GetInstance()); }
 
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+    void GetAllowedRouterIdRange(uint8_t *aMinRouterIdAllowed, uint8_t *aMaxRouterIdAllowed) const
```
Comment (abtink) [inline src/core/thread/router_table.hpp:342]: Use reference variable instead of pointer here?
I think we recommend reference use over pointer in c++ core API in our style guide.

File: src/core/thread/mle_router.cpp [hunk 7]
```diff
@@ -214,6 +214,9 @@ Error MleRouter::BecomeLeader(void)
     Router * router;
     uint32_t partitionId;
     uint8_t  leaderId;
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+    uint8_t minRouterIdAllowed, maxRouterIdAllowed;
```
Comment (abtink) [inline src/core/thread/mle_router.cpp:218]: One variable per line?

File: src/cli/cli.cpp [hunk 8]
```diff
@@ -3225,6 +3225,31 @@ otError Interpreter::ProcessParentPriority(Arg aArgs[])
 }
 #endif
 
+#if OPENTHREAD_FTD && OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+otError Interpreter::ProcessAllowRouterId(Arg aArgs[])
+{
+    uint8_t minRouterIdAllowed, maxRouterIdAllowed;
```
Comment (abtink) [inline src/cli/cli.cpp:3231]: One variable per line?

**Review by abtink — COMMENTED** [review]
Thanks @superwhd. Overall looks good.

Some smaller suggestions below. Thanks.

File: src/core/thread/router_table.hpp [hunk 9]
```diff
@@ -369,6 +390,10 @@ class RouterTable : public InstanceLocator, private NonCopyable
     TimeMilli        mRouterIdSequenceLastUpdated;
     uint8_t          mRouterIdSequence;
     uint8_t          mActiveRouterCount;
+#if OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+    uint8_t mMinRouterIdAllowed = 0;
+    uint8_t mMaxRouterIdAllowed = Mle::kMaxRouterId;
```
[the remark this answers is not in the document]
Comment (simonlingoogle) [reply src/core/thread/router_table.hpp]: Is it better (more clear) to initialize here?

What's the suggested way of doing it in C++?

[the remark this answers is not in the document]
Comment (abtink) [reply src/core/thread/router_table.hpp]: C++11 allows this model of default member variable initialization (though it is not possible for certain types, e.g., bit-fields) and we can mix and match (some variable use default initialization, some from constructor).
It is also possible to include both then the one from constructor wins:

> If a member has a default member initializer and also appears in the member initialization list in a constructor, the default member initializer is ignored for that constructor. [[link](https://en.cppreference.com/w/cpp/language/data_members#Member_initialization)]

In my opinion, it may be better to do all members initializations from one place (easer to see and read). Since we do need the constructor (typically to init the base class), it make sense to do all inits from the constructor.

File: src/core/thread/router_table.cpp [hunk 10]
```diff
@@ -529,6 +541,27 @@ void RouterTable::HandleTimeTick(void)
...
+void RouterTable::GetAllowedRouterIdRange(uint8_t &aMinRouterIdAllowed, uint8_t &aMaxRouterIdAllowed) const
+{
+    aMinRouterIdAllowed = mMinRouterIdAllowed;
+    aMaxRouterIdAllowed = mMaxRouterIdAllowed;
+}
+
+Error RouterTable::SetAllowedRouterIdRange(uint8_t aMinRouterIdAllowed, uint8_t aMaxRouterIdAllowed)
+{
+    otError error = OT_ERROR_NONE;
```
Comment (abtink) [inline src/core/thread/router_table.cpp:553]:
```suggestion
    Error error = kErrorNone;
```

**Review by abtink — APPROVED** [review]
LGTM. Thanks. 👍 

One small suggestion below.

File: include/openthread/thread_ftd.h [hunk 11]
```diff
@@ -739,6 +739,40 @@ void otThreadRegisterNeighborTableCallback(otInstance *aInstance, otNeighborTabl
  */
 void otThreadSetCcmEnabled(otInstance *aInstance, bool aEnabled);
 
+/**
+ * This function gets the range of router IDs that are allowed to assign to nodes within the thread network.
+ *
+ * @note This API requires `OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE`, and is only used for test purpose. All the
+ * router IDS in the range [aMinRouterIdAllowed, aMaxRouterIdAllowed] are allowed.
```
Comment (jwhui) [inline include/openthread/thread_ftd.h:746]:
```suggestion
 * router IDs in the range [aMinRouterIdAllowed, aMaxRouterIdAllowed] are allowed.
```

File: include/openthread/thread_ftd.h [hunk 12]
```diff
@@ -739,6 +739,40 @@ void otThreadRegisterNeighborTableCallback(otInstance *aInstance, otNeighborTabl
...
+ * @sa otThreadSetAllowedRouterIdRange
+ *
+ */
+void otThreadGetAllowedRouterIdRange(otInstance *aInstance, uint8_t *aMinRouterIdAllowed, uint8_t *aMaxRouterIdAllowed);
+
+/**
+ * This function sets the range of router IDs that are allowed to assign to nodes within the thread network.
+ *
+ * @note This API requires `OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE`, and is only used for test purpose. All the
+ * router IDS in the range [aMinRouterIdAllowed, aMaxRouterIdAllowed] are allowed.
```
Comment (jwhui) [inline include/openthread/thread_ftd.h:761]:
```suggestion
 * router IDs in the range [aMinRouterIdAllowed, aMaxRouterIdAllowed] are allowed.
```

File: src/cli/cli.hpp [hunk 13]
```diff
@@ -661,6 +664,9 @@ class Interpreter : public Output
     // Commands supported by radio:
     // [diag, help, reset, version]
     static constexpr Command sCommands[] = {
+#if OPENTHREAD_FTD && OPENTHREAD_CONFIG_REFERENCE_DEVICE_ENABLE
+        {"allowrouterid", &Interpreter::ProcessAllowRouterId},
```
Comment (jwhui) [inline src/cli/cli.hpp:668]: nit: how about rename to `routeridrange`?
```suggestion
        {"routeridrange", &Interpreter::ProcessAllowRouterId},
```

If you agree, also update the method to `ProcessRouterIdRange()`.

File: include/openthread/thread_ftd.h [hunk 14]
```diff
@@ -739,6 +739,40 @@ void otThreadRegisterNeighborTableCallback(otInstance *aInstance, otNeighborTabl
...
+ *
+ * @param[in]   aInstance            A pointer to an OpenThread instance.
+ * @param[out]  aMinRouterIdAllowed  The minimum router ID allowed.
+ * @param[out]  aMaxRouterIdAllowed  The maximum router ID allowed.
+ *
+ * @sa otThreadSetAllowedRouterIdRange
+ *
+ */
+void otThreadGetAllowedRouterIdRange(otInstance *aInstance, uint8_t *aMinRouterIdAllowed, uint8_t *aMaxRouterIdAllowed);
```
Comment (jwhui) [inline include/openthread/thread_ftd.h:755]: nit: slightly less verbose?
```suggestion
void otThreadGetRouterIdRange(otInstance *aInstance, uint8_t *aMinRouterIdAllowed, uint8_t *aMaxRouterIdAllowed);
```

File: include/openthread/thread_ftd.h [hunk 15]
```diff
@@ -739,6 +739,40 @@ void otThreadRegisterNeighborTableCallback(otInstance *aInstance, otNeighborTabl
...
+ * @param[in]  aMinRouterIdAllowed  The minimum router ID allowed.
+ * @param[in]  aMaxRouterIdAllowed  The maximum router ID allowed.
+ *
+ * @retval  OT_ERROR_NONE           Successfully set the range.
+ * @retval  OT_ERROR_INVALID_ARGS   aMinRouterIdAllowed > aMaxRouterIdAllowed, or the range is not covered by [0, 62].
+ *
+ * @sa otThreadGetAllowedRouterIdRange
+ *
+ */
+otError otThreadSetAllowedRouterIdRange(otInstance *aInstance,
```
Comment (jwhui) [inline include/openthread/thread_ftd.h:773]: nit: slightly less verbose?
```suggestion
otError otThreadSetRouterIdRange(otInstance *aInstance,
```

File: tests/scripts/thread-cert/backbone/test_dua_routing.py [hunk 16]
```diff
@@ -70,6 +70,7 @@ class TestNdProxy(thread_cert.TestCase):
             'is_otbr': True,
             'version': '1.2',
             'channel': CH1,
+            'allow_router_id': [0, 30],
```
Comment (jwhui) [inline tests/scripts/thread-cert/backbone/test_dua_routing.py:73]:
```suggestion
            'router_id_range': [0, 30],
```

**Review by jwhui — COMMENTED** [review]
Looks good overall. Added a few thoughts on naming.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼
