### PR TITLE
[time-sync] reset sequence upon joining a new partition & ensure leader is always authoritative

### LINKED ISSUE #3879: [time-sync] new devices joining a partition can cause the whole partition to lose synchronisation with the leader
**Describe the bug**

Device(s) holding a higher time sync sequence ID joins a partition. For example, the existing devices have just been been seeded by the leader with a time sync sequence of 10, and the new device(s) are seeding with a sequence ID of 136 as a relic from the previous partition. The existing devices, aside from the leader, accept and distribute the time synchronisation sequence, because they all consider it to be newer `(int8_t)(136 - 10) > 0` (see `time_sync_service.cpp` `HandleTimeSyncMessage()`). Take the case where the leader on the existing partition remains the same: none of the device(s) that just joined the partition are leaders. Now all devices aside from the leader have a time synchronisation based on the epoch of the previous partition, until the current leader seeds a time synchronisation with a time sequence ID greater than 136. In this case, with a time sync period of 30s, it will take 126 * 30 secs, i.e. 63 minutes before all the devices are in sync with the leader again. In the mean time, all devices aside from the leader will report `RESYNC_NEEDED` because nobody is actively seeding time sync with the epoch from the previous partition.

**To Reproduce**
Create a partition consisting of a few devices, their leader will begin seeding a time sync sequence from 0. In the mean time, configure another device and set `mTimeSyncSeq` in `time_sync_service.cpp` to be up to 127 greater than the current time sync sequence (use a dev board). This device will attach to the existing partition because it is bigger than the partition of the standalone device, so the leader shall remain the same. Observe the result.

**Expected behavior**
Perhaps upon joining a new partition, devices should reset their internal copy of `mTimeSyncSeq` to allow the leader on the partition they are joining to to seed them in all cases instead.

### PR DESCRIPTION
**Pull request by josephn123**
Fixes #3879 - [time-sync] new devices joining a partition can cause the whole partition to lose synchronisation with the leader

Also added some logging under the 'core' channel. I'm not sure if this is quite right but I always find myself having to add temporary logging when working on this, so would be good to include some permanently.

Also removed setting `mLastTimeSyncReceived` to the current time in the constructor. I think could have introduced a bug where a device joining a non-time sync capable partition would cause it to believe for a short period that it was synchronised.

### CODE REVIEW

File: src/core/thread/time_sync_service.cpp [hunk 1]
```diff
@@ -80,29 +79,49 @@ otNetworkTimeStatus TimeSync::GetTime(uint64_t &aNetworkTime) const
 void TimeSync::HandleTimeSyncMessage(const Message &aMessage)
 {
     const int64_t origNetworkTimeOffset = mNetworkTimeOffset;
+    int8_t        timeSyncSeqDelta;
 
     VerifyOrExit(aMessage.GetTimeSyncSeq() != OT_TIME_SYNC_INVALID_SEQ);
 
-    if (mTimeSyncSeq != OT_TIME_SYNC_INVALID_SEQ && (int8_t)(aMessage.GetTimeSyncSeq() - mTimeSyncSeq) < 0)
+    timeSyncSeqDelta = (int8_t)(aMessage.GetTimeSyncSeq() - mTimeSyncSeq);
```
Comment (jwhui) [inline src/core/thread/time_sync_service.cpp]: nit: prefer C++ style `static_cast`
