### PR TITLE
[mac] fix channel switching issue during energy scan

### LINKED ISSUE #9394: Channel switching issue in MAC layer occurs when there is no NW formation
**Description of the bug**
We encountered an issue while performing a scan energy without NW formation. The openthread stack follows two different flows for scan energy, with and without providing a time duration.

**1. scan energy without time duration**

- In this case, the MAC layer forces the firmware to change the channel by sending a spinel command (“cmd:PROP_VALUE_SET, key:PHY_CHAN,”).
> if (mChannel != aChannel)
{
error = Set(SPINEL_PROP_PHY_CHAN, SPINEL_DATATYPE_UINT8_S, aChannel);
SuccessOrExit(error);
mChannel = aChannel;
}

- Spinel property set handler updates the same channel to mReceiveChannel in link_raw.cpp

**2. scan energy with time duration**

- In this case, MAC layer calls energy scan to set 3 spinel property
> SuccessOrExit(error = Set(SPINEL_PROP_MAC_SCAN_MASK, SPINEL_DATATYPE_DATA_S, &aScanChannel, sizeof(uint8_t)));
SuccessOrExit(error = Set(SPINEL_PROP_MAC_SCAN_PERIOD, SPINEL_DATATYPE_UINT16_S, aScanDuration));
SuccessOrExit(error = Set(SPINEL_PROP_MAC_SCAN_STATE, SPINEL_DATATYPE_UINT8_S, SPINEL_SCAN_STATE_ENERGY));

- Spinel property set handler register one callback LinkRawEnergyScanDone to otLinkRawEnergyScan API

- LinkRawEnergyScanDone callback trigger otPlatRadioReceive with mReceiveChannel which updates the same channel in firmware.

- So when scan energy performs with time duration, it doesn't update mReceiveChannel for the callback.

Attached flow diagram for scan energy with zero/non-zero duration for reference.
ot-ch-update-flow

**To Reproduce**
After execution of the below commands,

1. **scan energy** -> `mChannel:25, aChannel:26, mReceiveChannel:26, fw Channel:26`
2. **scan energy 11** -> `mChannel:26 and aChannel:11, mReceiveChannel: 26, fw Channel: 26`
3. **scan energy** -> `mChannel:11, aChannel:11, mReceiveChannel:26`
In this scenario, mChannel and aChannel will be the same while scanning for channel 11, which means the MAC doesn't send a spinel command to update the channel. However, the firmware channel is still set to 26. As s result, the scan will be conducted for channel 26 instead of channel 11.

**Expected behavior**
The channel should be updated with the given channel in the MAC layer

**Fix**
To set the channel while scan energy with time duration, need to add the below lines in `PerformEnergyScan` (mac.cpp). 
Attached snap for reference.
>  if(!GetRxOnWhenIdle())
    {
        SuccessOrAssert(Get<Radio>().Receive(mScanChannel));
    }
image

### PR DESCRIPTION
**Pull request by hastigondaliya**
- This commit resolves inconsistency between Host and RCP channel on scan energy when network not created.
- Added fix in MAC layer to update the channel on scan energy

Fixes #9394

### CODE REVIEW

File: src/core/mac/mac.cpp [hunk 1]
```diff
@@ -340,6 +340,10 @@ void Mac::PerformEnergyScan(void)
     }
     else
     {
+        if(!GetRxOnWhenIdle())
+        {
+            SuccessOrAssert(Get().Receive(mScanChannel));
```
Comment (abtink) [inline src/core/mac/mac.cpp:345]: Should we do:
```suggestion
            mLinks.Receive(mScanChannel);
```

Comment (hastigondaliya) [reply src/core/mac/mac.cpp]: Hi @abtink,

Yes, We can do this way as well.

**Review by abtink — APPROVED** [review]
LGTM. Thanks.

File: src/core/mac/mac.cpp [hunk 2]
```diff
@@ -340,6 +340,10 @@ void Mac::PerformEnergyScan(void)
     }
     else
     {
+        if(!GetRxOnWhenIdle())
```
Comment (jwhui) [inline src/core/mac/mac.cpp:343]: To resolve pretty check:
```suggestion
        if (!GetRxOnWhenIdle())
```

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼
