### PR TITLE
[cc2538] fix FLASH settings location

### LINKED ISSUE #2069: cc2538 FLASH settings location
Probably for some historic reason, the location of the CC2538 FLASH settings is in the middle of the flash at address 0x00203900 - which if you turn on features, and turn the logs up the flash grows and then the two areas (code/text) vrs (settings) overlap and things go horribly wrong.

Most typically the initialized data goes bad at startup because the ".data" initializes are are stored at the END of the .text section, and thus these are the first to get wiped out, or partially wiped out depending upon how they align verses the page boundary. 

We have a fix for this but are not sure about the origins of the "0x39000" magic number in settings.cpp

Basically we move the SETTINGS storage to the *LAST* two pages  *END* of physical flash, just before the "CCA"  (customer configuration area) where FACTORY settings are normally stored)
thus the last 3 page are set aside as follows:

(N-1) = CCA area, length = 2k
(N-2) = Thread Settings Storage Area (B)
(N-3) = Thread Settings Storage Area (A)

### PR DESCRIPTION
**Pull request by DuaneEllis-TI**
Openthread settings are stored in onchip system flash in 2 pages (2K bytes each, total 4Kbytes), current location is at offset 0x03900 (physical location: 0x00239000 to 0x00239fff) which is near the center of the 512K bytes of available FLASH memory, as the application grows (ie: Compile: -Ofast vrs -Os [space], or turn on features [Lots of logging]) eventually the code grows and overflows address flash offset 0x03900

This moves the two pages to the last few pages of FLASH - specifically the page allocation is:
(N-3) - Settings Page A
(N-2) - Settings Page B
(N-1) - Physical last page of FLASH, also known as the CCA where various factory settings are stored.
Where N is the number of pages, which is either:  most commonly (512K/2K) or certain variants (256K/2K)

Resolves #2069.

### CODE REVIEW

File: examples/platforms/cc2538/flash.c [hunk 1]
```diff
@@ -26,25 +26,44 @@
...
 #include <fcntl.h>
 #include <stdio.h>
 #include <stdlib.h>
 #include <unistd.h>
 
-#include <openthread/config.h>
 #include <openthread/platform/alarm-milli.h>
 
 #include "platform-cc2538.h"
+#include "utils/wrap_string.h"
```
Comment (jwhui) [inline examples/platforms/cc2538/flash.c]: Current `STYLE_GUIDE.md` states to put these in alphabetical order.  Thoughts?

Comment (DuaneEllis-TI) [inline examples/platforms/cc2538/flash.c]: fixed

File: examples/platforms/cc2538/openthread-core-cc2538-config.h [hunk 2]
```diff
@@ -66,4 +66,23 @@
...
+ * @def SETTINGS_CONFIG_BASE_ADDRESS
+ *
+ * The actual physical address used for the cc2538 is set by the
+ * linker file, the value here is "relative to the base address" set
+ * in the linker file.
+ */
+#define SETTINGS_CONFIG_BASE_ADDRESS                           0
+
+/*
+ * The CC2538 linker script sets aside 2 pages.
```
Comment (DuaneEllis-TI) [inline examples/platforms/cc2538/openthread-core-cc2538-config.h]: fixed

File: examples/platforms/cc2538/cc2538-reg.h [hunk 3]
```diff
@@ -202,7 +202,7 @@
 #define SOC_ADC_ADCCON1_RCTRL0                  0x00000004  // ADCCON1 RCTRL bit 0
 #define SOC_ADC_ADCCON1_RCTRL1                  0x00000008  // ADCCON1 RCTRL bit 1
 
-#define FLASH_BASE                              0x00200000  // Flash base address
+// #define FLASH_BASE                              0x00200000  // Flash base address
```
Comment (DuaneEllis-TI) [inline examples/platforms/cc2538/cc2538-reg.h]: removed

File: examples/platforms/cc2538/openthread-core-cc2538-config.h [hunk 4]
```diff
@@ -66,4 +66,23 @@
...
+ * @def SETTINGS_CONFIG_BASE_ADDRESS
+ *
+ * The actual physical address used for the cc2538 is set by the
+ * linker file, the value here is "relative to the base address" set
+ * in the linker file.
+ */
+#define SETTINGS_CONFIG_BASE_ADDRESS                           0
+
+/**
+ * The CC2538 linker script sets aside 2 pages.
```
Comment (jwhui) [inline examples/platforms/cc2538/openthread-core-cc2538-config.h]: nit: `@def` here to be consistent

File: examples/platforms/cc2538/openthread-core-cc2538-config.h [hunk 5]
```diff
@@ -66,4 +66,23 @@
...
+ */
+#define SETTINGS_CONFIG_PAGE_NUM                               2
+
+/**
+ * The page size of settings, 2K bytes
```
Comment (jwhui) [inline examples/platforms/cc2538/openthread-core-cc2538-config.h]: nit: `@def` here to be consistent

File: examples/platforms/cc2538/openthread-core-cc2538-config.h [hunk 6]
```diff
@@ -66,4 +66,23 @@
...
+ */
+#define  SETTINGS_CONFIG_PAGE_SIZE                             2048
```
Comment (jwhui) [inline examples/platforms/cc2538/openthread-core-cc2538-config.h]: nit: single space after `#define` to be consistent

**Comment by DuaneEllis-TI** [comment]
@jwhui  -- fyi 

Strange - the POSIX side dies, and I touched *nothing* in the posix code.

https://travis-ci.org/openthread/openthread/jobs/262349254

This leads me to believe there are some timing and race conditions that are not yet known in the system.

Let me see if I can cause Travis to trigger again.

-Duane.

**Comment by jwhui** [comment]
@DuaneEllis-TI, yes we continue to see spurious failures on Travis.  Some of these are due to interactions with the simulation environment and Travis.  Others have been due to timing/race-conditions that are not properly handled in OpenThread.

**Comment by DuaneEllis-TI** [comment]
FYI the over the air commissioning process is full of these, it is no where near reliable enough to use.

**Comment by jwhui** [comment]
@DuaneEllis-TI, are there issues beyond what you've documented in #2037?  If so, please file GitHub Issues so we can track.
