### PR TITLE
[spinel] fix `printf` style output

### LINKED ISSUE #8402: [spinel] warnings in printf format string arguments
Hello,

It seems that changes done in this PR introduced some warnings in our NXP RT1060 ot_cli build: https://github.com/openthread/ot-nxp/actions/runs/3385088705/jobs/5622829631

The format of some arguments in logging functions is not correct. These warnings appear in the file "src/lib/spinel/radio_spinel_impl.hpp".

Are you aware of these warnings ? Can you take a look ? 

Thanks

_Originally posted by @chapongatien in https://github.com/openthread/openthread/issues/8356#issuecomment-1316752024_

### PR DESCRIPTION
**Pull request by jwhui**
Fixes #8402

### CODE REVIEW

**Review by abtink — APPROVED** [review]
LGTM. 👍

File: src/lib/spinel/radio_spinel_impl.hpp [hunk 1]
```diff
@@ -1677,7 +1677,7 @@ otError RadioSpinel<InterfaceType, ProcessContextType>::WaitResponse(void)
 {
     uint64_t end = otPlatTimeGet() + kMaxWaitTime * US_PER_MS;
 
-    otLogDebgPlat("Wait response: tid=%u key=%u", mWaitingTid, mWaitingKey);
+    otLogDebgPlat("Wait response: tid=%u key=%lu", mWaitingTid, ToUlong(mWaitingKey());
```
Comment (chapongatien) [inline src/lib/spinel/radio_spinel_impl.hpp:1680]: Should be ToUlong(mWaitingKey) instead of ToUlong(mWaitingKey**()**)

Comment (jwhui) [reply src/lib/spinel/radio_spinel_impl.hpp]: Thanks, fixed.

**Review by chapongatien — APPROVED** [review]
