### PR TITLE
[mle] properly handle cases where router table is not populated

### LINKED ISSUE #2748: [mle] assert in HandleAdvertisement method
During testing of ot-ncp-radio example, i got this assert on posix side:

`src/core/thread/mle_router.cpp:1270: otError ot::Mle::MleRouter::HandleAdvertisement(const ot::Message&, const ot::Ip6::MessageInfo&): Assertion "leader != NULL" failed.`

Unfortunatelly i couldn't reproduce it to pull more debug information.

Thoughts?

### PR DESCRIPTION
**Pull request by jwhui**
After attaching to a network, a device may need to wait until receiving the
next MLE Advertisement before populating the router table.

This commit makes the following changes:

- When receiving an MLE Advertisement, always process the Route TLV when the
  router table is not yet populated.

- Have RouterTable::GetLeaderAge() return max value when the router table
  is not yet populated.

- When generating a Connectivity TLV, populate the max routing cost when
  no leader information is available.

Resolves #2748.

### CODE REVIEW

File: src/core/thread/mle_router.cpp [hunk 1]
```diff
@@ -1192,7 +1192,8 @@ otError MleRouter::HandleAdvertisement(const Message &aMessage, const Ip6::Messa
     routerId = GetRouterId(sourceAddress.GetRloc16());
 
     if (IsFullThreadDevice() &&
-        static_cast<int8_t>(route.GetRouterIdSequence() - mRouterTable.GetRouterIdSequence()) > 0)
+        ((mRouterTable.GetActiveRouterCount() == 0) ||
+         (static_cast<int8_t>(route.GetRouterIdSequence() - mRouterTable.GetRouterIdSequence()) > 0)))
```
Comment (LuDuda) [inline src/core/thread/mle_router.cpp]: Just a question, do you think that to prevent assert on line 1278 it is enough to rely on `processRouteTlv` flag and `ProcessRouteTlv` method? Probably it is safe, but i see how it theoretically might fail:

a) if Advertisement has been received from other node than a parent (`processRouteTlv` would be set to false) - though probably it won't happen since we don't have links with other nodes at that stage
b) if Route64 does not include Leader Id - for whatever reason - fuzz tests might trigger this

If there is any chance of that i would replace `assert` with `VerifyOrExit`, else its fine 👍

Comment (jwhui) [reply src/core/thread/mle_router.cpp]: @LuDuda, thanks for pointing that out!  The related code is only used to update the path cost to the leader.  I added a check around that code to avoid processing if the leader is not in the router table.  Please review again.
