### PR TITLE
[spinel] remove incorrect static_cast

### LINKED ISSUE #8481: Incorrect static cast
**Describe the bug** 

git-commit 27b4314

https://github.com/openthread/openthread/blame/main/src/lib/spinel/radio_spinel_impl.hpp#L2216

```
template <typename InterfaceType, typename ProcessContextType>
uint64_t RadioSpinel<InterfaceType, ProcessContextType>::GetNow(void)
{
    return mIsTimeSynced ? (otPlatTimeGet() + static_cast<uint64_t>(mRadioTimeOffset)) : UINT64_MAX;
}
```
This should not be cast to an unsigned integer

if the `mRadioTimeOffset` is negative, the resulting time instance is incorrect and breaks e.g. CSL over RCP

### PR DESCRIPTION
**Pull request by thomas-tc2**
Fixes #8481

### CODE REVIEW

File: src/lib/spinel/radio_spinel_impl.hpp [hunk 1]
```diff
@@ -2213,7 +2213,19 @@ void RadioSpinel<InterfaceType, ProcessContextType>::CalcRcpTimeOffset(void)
 template <typename InterfaceType, typename ProcessContextType>
 uint64_t RadioSpinel<InterfaceType, ProcessContextType>::GetNow(void)
 {
-    return mIsTimeSynced ? (otPlatTimeGet() + static_cast<uint64_t>(mRadioTimeOffset)) : UINT64_MAX;
+    uint64_t now = UINT64_MAX;
+    if (mIsTimeSynced)
```
Comment (abtink) [inline src/lib/spinel/radio_spinel_impl.hpp:2217]: Thanks @thcu-gp .

Can we instead define `mRadioTimeOffset` as `uint64` directly (instead of `int64_t`).

We calculate it as
``` 
mRadioTimeOffset  = (remoteTimestamp - ((localRxTimestamp / 2) + (localTxTimestamp / 2)));
```
where everything is `uint64_t` already and later we use

```
otPlatTimeGet() + mRadioTimeOffset
```

I think the calculations would be correct even if the result of subtractions is effectively negative (as long as all the calculations are using `uint64_t`).

Comment (thcu-gp) [reply src/lib/spinel/radio_spinel_impl.hpp:2217]: I can give it a whirl (probably somewhere next week)

**Review by abtink — APPROVED** [review]
Thanks. LGTM.

**Review by bukepo — APPROVED** [review]

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼
