### PR TITLE
[tcat][ble] fixes to connection state mgmt and Disconnect cmd; comments updated

### LINKED ISSUE #10196: TCAT TLS connection setup: inconsistent state
**Describe the bug** 
If a TCAT Commissioner connects via TLS, and the handshake succeeds, but the `mTcatAgent.Connected(mTls)` setup routine for the TCAT agent fails with an error, then the state becomes inconsistent: the Commissioner thinks it is successfully connected. The TCAT Device has its TLS connection established but TCAT Agent is inactive so won't process any commands.

**To Reproduce**
(No details given) Connect using a TCAT Commissioner certificate that would fails the checks in `Error TcatAgent::Connected(MeshCoP::SecureTransport &aTlsContext)` .

1. Git commit id: ee83d45f7697d8a28707e28d56b2d5c715259617
2. IEEE 802.15.4 hardware platform: `simulation`
3. Build steps: `./script/cmake-build simulation -DOT_FULL_LOGS=ON`
4. Network topology: single simulated node

**Expected behavior** 
Fate-sharing: if TCAT Device rejects the Commissioner, close the TLS, and send alert to Commissioner.  Vice versa if Commissioner rejects the Device, send alert to Device (haven't checked that side yet).

Expect that the return status of [this line](https://github.com/openthread/openthread/blob/ee83d45f7697d8a28707e28d56b2d5c715259617/src/core/radio/ble_secure.cpp#L333C16-L333C59) is used:

```
            IgnoreReturnValue(mTcatAgent.Connected(mTls));
```

**Console/log output** 
(TBD) I'll work on a first fix/PR of this issue in order to proceed with the work on TCAT certificates.

**Additional context** Add any other context about the problem here.
(TBD) I'll work on a first fix/PR of this issue in order to proceed with the work on TCAT certificates.

### PR DESCRIPTION
**Pull request by EskoDijk**
* Fixes to connection state management and handling of Disconnect command TLV
   * specifically, this now ensures that TCAT remains on (started) after a commissioner disconnects. Earlier, there was the problem that the 2nd commissioner couldn't connect anymore.
   * specifically, in `ble_secure.cpp` the check for `if (mTcatAgent.IsEnabled())` is removed, since the `err = mTcatAgent.Connected(mTls)` will already check this and raise an error if not enabled. If not enabled, the Device is in a wrong state to handle TCAT Commissioner commands so now it closes the connection right away. That's better than to leave the Commissioner in limbo on the TLS connection. The Commissioner can now retry again and all will be well again.
   * timeout of at most 10 seconds on UDP write operation in simulation mode (if longer, the TCAT device isn't reachable and the Commissioner now shows the error to the user.) Earlier, it got stuck forever.
* Corrects some copy/paste errors in API definitions in comments; adds comments where needed to explain.
   * adds whitespace at some places to align format with rest of code
* improved some of the --debug output for the UDP simulation mode of the TCAT Commissioner.

fixes the lingering issues of #10196 (main issue was already fixed)
close #10196

### CODE REVIEW

**Comment by EskoDijk** [comment]
@canisLupus1313 FYI - here some fixes to the TCAT Commissioner/Device which improve the behavior in simulation mode. Now it works for me without "hang-ups" of the Commissioner.

**Review by abtink — APPROVED** [review]
LGTM. Thanks.

**Review by jwhui — APPROVED** [review]
Thanks! 👍🏼

File: src/core/meshcop/tcat_agent.cpp [hunk 1]
```diff
@@ -389,6 +389,7 @@ Error TcatAgent::HandleSingleTlv(const Message &aIncomingMessage, Message &aOutg
         {
         case kTlvDisconnect:
             error = kErrorAbort;
+            response = true; // true - to avoid response-with-status being sent.
```
Comment (jwhui) [inline src/core/meshcop/tcat_agent.cpp:392]: nit: to fix the pretty check
```suggestion
            error    = kErrorAbort;
            response = true; // true - to avoid response-with-status being sent.
```

Comment (EskoDijk) [reply src/core/meshcop/tcat_agent.cpp]: nit fixed now!
